(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.fondo2 = function() {
	this.initialize(img.fondo2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,635,400);


(lib.fondo1 = function() {
	this.initialize(img.fondo1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,600);


(lib.logotipoprincipalofipol04 = function() {
	this.initialize(img.logotipoprincipalofipol04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,250,54);


(lib.policias = function() {
	this.initialize(img.policias);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,208,200);


(lib.Recurso125años = function() {
	this.initialize(img.Recurso125años);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,200);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Símbolo11 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFD900").s().p("AgcBtIAAjYIA5AAIAADYg");
	this.shape.setTransform(85.925,28.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFD900").s().p("AgTBPQgkAAgSgMQgZgRAAgsIAAgOQAAgoAUgRQAQgNAjAAIAnAAQAwAAASANQAVAPAAAmIAAAZIiLAAIAAAJQAAAMAJAFQAIAEASAAIARAAQAVAAAHgFQAFgEAAgJIA2AAIAAAHQAAAbgXALQgRAJgkAAgAArgVQAAgNgIgEQgIgEgaAAQgbAAgHAEQgHAEAAANIBTAAIAAAAg");
	this.shape_1.setTransform(69.625,31.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFD900").s().p("AgjBNIhJiYIA+AAIAuBrIAuhrIA/AAIhJCYg");
	this.shape_2.setTransform(47.4,31.85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFD900").s().p("AgcBtIAAiYIA5AAIAACYgAgcg/IAAgsIA5AAIAAAsg");
	this.shape_3.setTransform(31.075,28.65);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFD900").s().p("AAtBOIAAhXQAAgXglAAIgNAAQgnAAAAAhIAABNIg5AAIAAiYIA5AAIAAAYIABAAQAHgPAQgGQANgGAYAAQAmAAASAJQAdAPAAAsIAABXg");
	this.shape_4.setTransform(13.675,31.725);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFD900").s().p("AgqBPQg/AAAAg9IAAgkQAAg8A/AAIBVAAQA/AAAAA8IAAAkQAAA9g/AAgAgmgdQgKAHAAAQIAAANQAAAQAKAHQAJAFAVAAIAMAAQAcABAIgFQAJgFAAgPIAAgVQAAgPgJgFQgIgEgcgBIgMAAQgVABgJAFg");
	this.shape_5.setTransform(-25.575,31.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFD900").s().p("AADBgQhBAAAAg2IAAg7IgcAAIAAgqIAcAAIAAgkIA6AAIAAAkIBYAAIAAAqIhYAAIAAA6QAAANAVAAQAOAAAFgEQAFgDAAgLIAAgKIAyAAIAAASQAAAXgPAOQgRAPghAAg");
	this.shape_6.setTransform(-48.175,30.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFD900").s().p("AgcBtIAAjYIA5AAIAADYg");
	this.shape_7.setTransform(-62.975,28.65);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFD900").s().p("AgrBPQgcAAgNgIQgQgLAAgZIAAgMQAAgcAVgJQAQgGAvgBQAaAAALACQAOADAIAIIAAgNQAAgMgFgFQgGgEgQAAIghAAQgMAAgFACQgFADAAAHIg3AAQAAgdAPgKQAOgJAnAAIBDAAQA8AAAAA3IAABkIg3AAIAAgSQgMANgIADQgKAEgTAAgAgnAPQgFAEgBAKQABAIAGADQAHADAQAAIAQAAQAbAAAKgEQAGgEAAgJQAAgIgFgEQgHgDgXAAIgYAAQgRAAgHAEg");
	this.shape_8.setTransform(-79.95,31.85);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFD900").s().p("AgTBPQgkAAgSgMQgZgQAAgsIAAgOQAAgpAUgQQAQgOAjAAIAnAAQAwAAASANQAVAOAAAnIAAAZIiLAAIAAAJQAAAMAJAEQAIAFASAAIARAAQAVAAAHgGQAFgDAAgIIA2AAIAAAGQAAAbgXALQgRAJgkAAgAArgVQAAgNgIgEQgIgEgaAAQgbAAgHAEQgHADAAAOIBTAAIAAAAg");
	this.shape_9.setTransform(97.025,-0.15);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFD900").s().p("AgVBuQgzAAgSgSQgNgOAAghIAAgcQAAghANgNQASgSAzAAIARAAQAuAAAEAeIABAAIAAhcIA5AAIAADYIg2AAIAAgcIAAAAQgKAfgtAAgAgrACQgFAFAAAPIAAASQAAAOAFAFQAHAHATAAIAhAAQASAAAIgFQAIgGAAgRIAAgPQAAgQgIgHQgIgEgSAAIghAAQgTAAgHAGg");
	this.shape_10.setTransform(73.475,-3.225);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFD900").s().p("AgcBsIAAjYIA5AAIAADYg");
	this.shape_11.setTransform(41.475,-3.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFD900").s().p("AgqBPQgdAAgOgIQgPgLAAgYIAAgOQAAgbAVgJQAPgHAxAAQAZABALACQAPACAIAIIAAgOQAAgLgGgEQgGgFgQAAIggAAQgOAAgDACQgFADgBAHIg4AAQABgdAQgLQAOgIAnAAIBBAAQA9AAAAA3IAABjIg2AAIAAgRQgNANgIADQgKAEgUAAgAgnAQQgGADABAKQgBAHAHADQAHAEAQAAIARAAQAbAAAJgFQAHgDAAgIQAAgJgGgEQgHgDgWAAIgZAAQgSAAgGAFg");
	this.shape_12.setTransform(24.5,-0.15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFD900").s().p("AhUBOIAAiYIA2AAIAAAdIABAAQAJggAuAAQAfAAAOAPQANAOAAAgIAAANIgyAAQAAgQgFgGQgGgHgRAAQggAAAAAaIAABUg");
	this.shape_13.setTransform(3.8,-0.275);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFD900").s().p("AgpBpQgfAAgNgKQgQgLAAgcIA7AAQAAAMAOABIApAAQAUAAAIgIQAJgIAAgTIAAgJQgJAJgJACQgLAEgVAAIgeAAQgpAAgRgQQgPgPAAgfIAAgWQAAghASgOQAPgMAlAAIAhAAQAVgBAJAFQAJAEALAPIAAAAIAAgVIA2AAIAACPQAAAcgOAPQgTAUgxAAgAgpg3QgHAGAAASQAAASAHAGQAIAHAVAAIAbAAQAVAAAHgHQAHgGAAgSQAAgSgHgGQgHgHgVAAIgbAAQgVAAgIAHg");
	this.shape_14.setTransform(-19.075,2.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFD900").s().p("AgTBPQgkAAgSgMQgZgQAAgsIAAgOQAAgpAUgQQAQgOAjAAIAnAAQAwAAASANQAVAOAAAnIAAAZIiLAAIAAAJQAAAMAJAEQAIAFASAAIARAAQAVAAAHgGQAFgDAAgIIA2AAIAAAGQAAAbgXALQgRAJgkAAgAArgVQAAgNgIgEQgIgEgaAAQgbAAgHAEQgHADAAAOIBTAAIAAAAg");
	this.shape_15.setTransform(-42.225,-0.15);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFD900").s().p("AADBgQhBAAAAg2IAAg7IgcAAIAAgqIAcAAIAAgkIA6AAIAAAkIBYAAIAAAqIhYAAIAAA6QAAANAVAAQAOAAAFgEQAFgDAAgLIAAgKIAyAAIAAASQAAAXgPAOQgRAPghAAg");
	this.shape_16.setTransform(-63.725,-1.825);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFD900").s().p("AAtBOIAAhXQAAgXglAAIgNAAQgnAAAAAhIAABNIg5AAIAAiYIA5AAIAAAYIABAAQAHgPAQgGQANgGAYAAQAmAAASAJQAdAPAAAsIAABXg");
	this.shape_17.setTransform(-85.575,-0.275);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFD900").s().p("AgcBsIAAiYIA5AAIAACYgAgcg/IAAgtIA5AAIAAAtg");
	this.shape_18.setTransform(-102.975,-3.35);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFD900").s().p("AAtBOIAAhXQAAgXglAAIgNAAQgnAAAAAhIAABNIg5AAIAAiYIA5AAIAAAYIABAAQAHgPAQgGQANgGAYAAQAmAAASAJQAdAPAAAsIAABXg");
	this.shape_19.setTransform(109.975,-32.275);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFD900").s().p("AgqB4Qg/AAAAg8IAAglQAAg8A/AAIBVAAQA/AAAAA8IAAAlQAAA8g/AAgAgmAMQgKAGAAAQIAAAOQAAAQAKAHQAJAGAVAAIAMAAQAcAAAIgFQAJgFAAgPIAAgVQAAgQgJgEQgIgFgcAAIgMAAQgVAAgJAGgAgkg8IAlg7IBJAAIg/A7g");
	this.shape_20.setTransform(85.525,-36.275);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFD900").s().p("AgcBtIAAiYIA5AAIAACYgAgcg/IAAgsIA5AAIAAAsg");
	this.shape_21.setTransform(68.125,-35.35);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFD900").s().p("AgXBPQgkAAgRgMQgZgRAAgsIAAgOQAAgoATgRQARgNAjAAIA/AAQBFAAAAAzIAAAOIg4AAQAAgMgHgFQgHgFgTAAIgVAAQgkAAAAAYIAAATQAAAaAfAAIAcAAQAfAAAAgSIAAgDIA4AAIAAANQAAAcgVAOQgRALgdAAg");
	this.shape_22.setTransform(51.475,-32.15);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFD900").s().p("AgqBPQgeAAgNgIQgPgLAAgZIAAgMQAAgcAVgJQAQgGAvAAQAaAAALABQAOADAJAIIAAgNQAAgMgGgFQgGgEgQAAIggAAQgOAAgDACQgFACgBAJIg4AAQABgeAPgLQAOgIAoAAIBBAAQA9AAAAA3IAABkIg3AAIAAgSQgMANgIADQgJAEgVAAgAgnAPQgGAEABAKQAAAHAGAEQAHADAQAAIARAAQAaAAAKgEQAGgEABgJQgBgIgFgDQgHgEgWAAIgZAAQgSAAgGAEg");
	this.shape_23.setTransform(28.2,-32.15);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFD900").s().p("AhUBOIAAiYIA2AAIAAAdIABAAQAJggAuAAQAgAAANAPQANAOAAAgIAAANIgyAAQAAgQgFgGQgGgHgQAAQghAAAAAaIAABUg");
	this.shape_24.setTransform(7.5,-32.275);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFD900").s().p("AgqBPQgdAAgOgIQgPgLAAgZIAAgMQAAgcAVgJQAPgGAxAAQAZAAALABQAPADAHAIIAAgNQABgMgGgFQgFgEgRAAIggAAQgNAAgEACQgGACAAAJIg4AAQABgeAQgLQAOgIAnAAIBBAAQA9AAAAA3IAABkIg2AAIAAgSQgNANgIADQgJAEgVAAgAgnAPQgGAEABAKQgBAHAHAEQAHADARAAIAQAAQAbAAAJgEQAHgEAAgJQAAgIgGgDQgHgEgWAAIgZAAQgSAAgGAEg");
	this.shape_25.setTransform(-14.75,-32.15);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFD900").s().p("AhnBoIAAjNIA3AAIAAAXIABAAQANgaAoAAIAQAAQAzABASARQANAOAAAiIAAAbQAAAhgNAOQgSASgzAAIgLAAQgYAAgLgGQgMgFgJgTIgBAAIAABQgAglg3QgJAGAAARIAAAPQAAARAJAEQAIAGASAAIAdAAQATAAAHgHQAFgEAAgOIAAgSQAAgPgFgFQgHgHgTAAIgdAAQgSAAgIAFg");
	this.shape_26.setTransform(-37.925,-29.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFD900").s().p("AgTBPQgkAAgSgMQgZgRAAgsIAAgOQAAgoAUgRQAQgNAjAAIAnAAQAwAAASANQAVAPAAAmIAAAZIiLAAIAAAJQAAAMAJAFQAIAEASAAIARAAQAVAAAHgGQAFgDAAgJIA2AAIAAAHQAAAbgXALQgRAJgkAAgAArgUQAAgOgIgEQgIgEgaAAQgbAAgHAEQgHAEAAAOIBTAAIAAAAg");
	this.shape_27.setTransform(-61.475,-32.15);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFD900").s().p("AhUBOIAAiYIA2AAIAAAdIABAAQAJggAuAAQAfAAAOAPQANAOAAAgIAAANIgyAAQAAgQgFgGQgGgHgRAAQggAAAAAaIAABUg");
	this.shape_28.setTransform(-82.15,-32.275);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFD900").s().p("AiBBtIAAjYIC1AAQAsgBATAVQAPASAAAkIAAASQAAAcgNASQgQAXggAAIiEAAIAAA3gAg/AAIBnAAQAWAAgBgWIAAgJQAAgWgbAAIhhAAg");
	this.shape_29.setTransform(-106.95,-35.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-159.5,-49,319.1,98);


(lib.Símbolo10 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFD900").s().p("AgfBPQgoAAgQgLQgRgLAAgcIA8AAQAAAHAFADQAIAEAXAAIATAAQAUAAAHgCQAIgDAAgGQAAgHgGgDQgFgDgOAAIg2AAQgoAAgOgMQgPgKgBgfQAAgbAVgKQAPgHAjAAIAnAAQA3AAASAKQAQAJAAAcIg6AAQgBgHgIgCQgHgCgZAAQgaAAgGACQgIACAAAIQAAAFAGACQAHACAWAAIAmAAQAwgBAPAQQALAJAAAZQAAAegPALQgRAKgxAAg");
	this.shape.setTransform(137,31.85);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFD900").s().p("AgqBPQg/AAAAg9IAAgkQAAg8A/AAIBVAAQA/AAAAA8IAAAkQAAA9g/AAgAgmgdQgKAHAAAQIAAANQAAAQAKAHQAJAFAVAAIAMAAQAcABAIgFQAJgFAAgPIAAgVQAAgPgJgFQgIgEgcgBIgMAAQgVABgJAFg");
	this.shape_1.setTransform(112.925,31.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFD900").s().p("AgVBuQgzAAgSgSQgNgOAAghIAAgcQAAghANgNQASgSAzAAIARAAQAuAAAEAeIABAAIAAhcIA5AAIAADYIg2AAIAAgcIAAAAQgKAfgtAAgAgrACQgFAFAAAPIAAASQAAAOAFAFQAHAHATAAIAhAAQASAAAIgFQAIgGAAgRIAAgPQAAgQgIgHQgIgEgSAAIghAAQgTAAgHAGg");
	this.shape_2.setTransform(88.275,28.775);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFD900").s().p("AgqBPQgdAAgOgIQgPgLAAgZIAAgMQAAgcAVgJQAPgGAxgBQAZAAALACQAPADAHAIIAAgNQABgMgGgFQgFgEgRAAIggAAQgNAAgEACQgGADAAAHIg4AAQABgdAQgKQAOgJAnAAIBBAAQA9AAAAA3IAABkIg2AAIAAgSQgNANgIADQgJAEgVAAgAgnAPQgGAEABAKQgBAIAHADQAHADARAAIAQAAQAbAAAJgEQAHgEAAgJQAAgIgGgEQgHgDgWAAIgZAAQgSAAgGAEg");
	this.shape_3.setTransform(64.45,31.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFD900").s().p("AhYBNIAAgnIBdhKIAAAAIhYAAIAAgnICnAAIAAAtIhXBCIAAABIBcAAIAAAog");
	this.shape_4.setTransform(43.7,31.85);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFD900").s().p("AgcBtIAAiYIA5AAIAACYgAgcg/IAAgsIA5AAIAAAsg");
	this.shape_5.setTransform(28.875,28.65);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFD900").s().p("AgcBtIAAjYIA5AAIAADYg");
	this.shape_6.setTransform(18.525,28.65);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFD900").s().p("AgqBPQgdAAgOgIQgPgLAAgZIAAgMQAAgcAVgJQAPgGAxgBQAZAAALACQAPADAIAIIAAgNQAAgMgGgFQgGgEgQAAIggAAQgOAAgDACQgFADgBAHIg4AAQABgdAQgKQAOgJAnAAIBBAAQA9AAAAA3IAABkIg2AAIAAgSQgNANgIADQgKAEgUAAgAgnAPQgGAEABAKQgBAIAHADQAHADARAAIAQAAQAbAAAJgEQAHgEAAgJQAAgIgGgEQgHgDgWAAIgZAAQgSAAgGAEg");
	this.shape_7.setTransform(1.55,31.85);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFD900").s().p("AAtBOIAAhXQAAgXglAAIgNAAQgnAAAAAhIAABNIg5AAIAAiYIA5AAIAAAYIABAAQAHgPAQgGQANgGAYAAQAmAAASAJQAdAPAAAsIAABXg");
	this.shape_8.setTransform(-21.825,31.725);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFD900").s().p("AgqBPQg/AAAAg9IAAgkQAAg8A/AAIBVAAQA/AAAAA8IAAAkQAAA9g/AAgAgmgdQgKAHAAAQIAAANQAAAQAKAHQAJAFAVAAIAMAAQAcABAIgFQAJgFAAgPIAAgVQAAgPgJgFQgIgEgcgBIgMAAQgVABgJAFg");
	this.shape_9.setTransform(-46.275,31.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFD900").s().p("AgfBPQgoAAgQgLQgRgLAAgcIA8AAQAAAHAFADQAIAEAXAAIATAAQAVAAAGgCQAIgDAAgGQAAgHgGgDQgFgDgPAAIg1AAQgoAAgPgMQgPgKAAgfQABgbAUgKQAPgHAjAAIAnAAQA3AAASAKQAQAJAAAcIg6AAQgCgHgHgCQgHgCgZAAQgaAAgGACQgIACAAAIQAAAFAGACQAHACAWAAIAmAAQAwgBAPAQQALAJAAAZQAAAegPALQgRAKgxAAg");
	this.shape_10.setTransform(-70.35,31.85);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFD900").s().p("AhTBOIAAiYIA2AAIAAAdIAAAAQAJggAuAAQAgAAANAPQANAOAAAgIAAANIgyAAQAAgQgFgGQgGgHgQAAQghAAAAAaIAABUg");
	this.shape_11.setTransform(-91.75,31.725);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFD900").s().p("AgTBPQgkAAgSgMQgZgRAAgsIAAgOQAAgoAUgRQAQgNAjAAIAnAAQAwAAASANQAVAPAAAmIAAAZIiLAAIAAAJQAAAMAJAFQAIAEASAAIARAAQAVAAAHgFQAFgEAAgJIA2AAIAAAHQAAAbgXALQgRAJgkAAgAArgVQAAgNgIgEQgIgEgaAAQgbAAgHAEQgHAEAAANIBTAAIAAAAg");
	this.shape_12.setTransform(-113.325,31.85);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFD900").s().p("AhnBoIAAjNIA3AAIAAAXIABAAQANgZAogBIAQAAQAzABASARQANAOAAAiIAAAbQAAAhgNAOQgSASgzAAIgLAAQgYAAgLgGQgMgFgJgTIgBAAIAABQgAglg3QgJAGAAARIAAAPQAAAQAJAFQAIAGASAAIAdAAQATAAAHgHQAFgEAAgOIAAgSQAAgPgFgFQgHgHgTAAIgdAAQgSAAgIAFg");
	this.shape_13.setTransform(-136.475,34.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFD900").s().p("AgqBPQg/AAAAg8IAAgkQAAg9A/AAIBVAAQA/AAAAA9IAAAkQAAA8g/AAgAgmgcQgKAGAAAQIAAANQAAAQAKAGQAJAHAVAAIAMAAQAcgBAIgEQAJgFAAgQIAAgTQAAgQgJgFQgIgEgcAAIgMAAQgVgBgJAHg");
	this.shape_14.setTransform(64.775,-0.15);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFD900").s().p("Ag6BmIAAglIAGAAQAlAAAAgWIgVAAIhFiRIA+AAIArBpIAshpIA+AAIhVC0QgNAZgqAAg");
	this.shape_15.setTransform(41.85,2.525);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFD900").s().p("AgqBPQg/AAAAg8IAAgkQAAg9A/AAIBVAAQA/AAAAA9IAAAkQAAA8g/AAgAgmgcQgKAGAAAQIAAANQAAAQAKAGQAJAHAVAAIAMAAQAcgBAIgEQAJgFAAgQIAAgTQAAgQgJgFQgIgEgcAAIgMAAQgVgBgJAHg");
	this.shape_16.setTransform(18.875,-0.15);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFD900").s().p("AhnBpIAAjOIA3AAIAAAXIABAAQANgZAoAAIAQAAQAzgBASATQANANAAAiIAAAcQAAAggNANQgSASgzAAIgLAAQgYAAgLgFQgMgFgJgSIgBAAIAABQgAglg3QgJAHAAAQIAAAPQAAAQAJAGQAIAFASAAIAdAAQATAAAHgHQAFgEAAgPIAAgSQAAgOgFgGQgHgGgTAAIgdAAQgSAAgIAFg");
	this.shape_17.setTransform(-5.375,2.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFD900").s().p("AgqBPQgdAAgOgIQgPgLAAgYIAAgOQAAgbAVgJQAPgHAxAAQAZABALACQAPACAHAIIAAgOQABgLgGgEQgFgFgRAAIggAAQgNAAgEACQgGADAAAHIg4AAQABgdAQgLQAOgIAnAAIBBAAQA9AAAAA3IAABjIg2AAIAAgRQgNANgIADQgJAEgVAAgAgnAQQgGADABAKQgBAHAHADQAHAEARAAIAQAAQAbAAAJgFQAHgDAAgIQAAgJgGgEQgHgDgWAAIgZAAQgSAAgGAFg");
	this.shape_18.setTransform(-29.6,-0.15);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFD900").s().p("Ag5BmIAAglIAEAAQAmAAAAgWIgVAAIhFiRIA+AAIArBpIAshpIA+AAIhVC0QgNAZgqAAg");
	this.shape_19.setTransform(-66.25,2.525);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFD900").s().p("AgqBPQg/AAAAg9IAAgkQAAg8A/AAIBVAAQA/AAAAA8IAAAkQAAA9g/AAgAgmgdQgKAHAAAQIAAANQAAAQAKAHQAJAFAVAAIAMAAQAcABAIgFQAJgFAAgQIAAgUQAAgPgJgEQgIgFgcgBIgMAAQgVABgJAFg");
	this.shape_20.setTransform(112.975,-32.15);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFD900").s().p("AADBgQhBAAAAg2IAAg7IgcAAIAAgqIAcAAIAAgkIA6AAIAAAkIBYAAIAAAqIhYAAIAAA6QAAANAVAAQAOAAAFgEQAFgDAAgLIAAgKIAyAAIAAASQAAAXgPAOQgRAPghAAg");
	this.shape_21.setTransform(90.375,-33.825);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFD900").s().p("AAtBOIAAhXQAAgXglAAIgNAAQgnAAAAAhIAABNIg5AAIAAiYIA5AAIAAAYIABAAQAHgPAQgGQANgGAYAAQAmAAASAJQAdAPAAAsIAABXg");
	this.shape_22.setTransform(68.525,-32.275);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFD900").s().p("AgTBPQgkAAgSgMQgZgRAAgsIAAgOQAAgoAUgRQAQgNAjAAIAnAAQAwAAASANQAVAPAAAmIAAAZIiLAAIAAAJQAAAMAJAFQAIAEASAAIARAAQAVAAAHgGQAFgDAAgJIA2AAIAAAHQAAAbgXALQgRAJgkAAgAArgUQAAgOgIgEQgIgEgaAAQgbAAgHAEQgHAEAAAOIBTAAIAAAAg");
	this.shape_23.setTransform(45.175,-32.15);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFD900").s().p("AgcBtIAAiYIA5AAIAACYgAgcg/IAAgsIA5AAIAAAsg");
	this.shape_24.setTransform(28.875,-35.35);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFD900").s().p("ABrBOIAAhRQAAgRgHgFQgIgHgYAAQgVAAgJAGQgJAGAAAPIAABTIg5AAIAAhWQAAgOgIgFQgHgFgbAAQgTAAgIAGQgJAHAAARIAABQIg5AAIAAiYIA2AAIAAAeIABAAQAFghAuAAIAWAAQAoAAAPAkQAIgVAMgHQALgIAZAAIARAAQAmAAASATQAPAQAAAjIAABVg");
	this.shape_25.setTransform(5.55,-32.275);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFD900").s().p("AgcBtIAAiYIA5AAIAACYgAgcg/IAAgsIA5AAIAAAsg");
	this.shape_26.setTransform(-17.775,-35.35);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFD900").s().p("AhIBFQgdgPAAgsIAAhXIA5AAIAABXQAAAXAlAAIAMAAQAoAAAAghIAAhNIA5AAIAACYIg5AAIAAgYIgBAAQgHAPgQAGQgNAGgYAAQgmAAgSgJg");
	this.shape_27.setTransform(-35.175,-32.025);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFD900").s().p("AgpBoQgfAAgNgJQgQgLAAgbIA7AAQAAAMAOgBIApAAQAUAAAIgHQAJgIAAgTIAAgKQgJAJgJAEQgLADgVAAIgeAAQgpAAgRgQQgPgPAAggIAAgUQAAgjASgNQAPgNAlAAIAhAAQAVABAJAEQAJAEALAPIAAAAIAAgVIA2AAIAACOQAAAdgOAPQgTATgxAAgAgpg3QgHAGAAASQAAASAHAGQAIAHAVAAIAbAAQAVAAAHgHQAHgGAAgSQAAgSgHgGQgHgHgVAAIgbAAQgVAAgIAHg");
	this.shape_28.setTransform(-59.825,-29.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFD900").s().p("AgTBPQgkAAgSgMQgZgRAAgsIAAgOQAAgoAUgRQAQgNAjAAIAnAAQAwAAASANQAVAPAAAmIAAAZIiLAAIAAAJQAAAMAJAFQAIAEASAAIARAAQAVAAAHgGQAFgDAAgJIA2AAIAAAHQAAAbgXALQgRAJgkAAgAArgUQAAgOgIgEQgIgEgaAAQgbAAgHAEQgHAEAAAOIBTAAIAAAAg");
	this.shape_29.setTransform(-82.975,-32.15);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFD900").s().p("AgzBvQgvAAgSgLQgUgOAAghIAAgPIBDAAQAAAQAHAEQAFAFARAAIBQAAQANAAAHgEQAIgDABgMQgBgHgCgEQgDgEgJgCQgOgDhAAAQhJAAgVgNQgLgGgDgMQgDgLgBgXQAAgkAMgNQATgUA5AAIBcAAQA0AAATARQANAOAAAhIAAAHIhDAAQABgNgGgEQgGgGgVABIhJAAQgZgBAAASQAAAHADAEQACADAIACQALACA2ABQBRgBAWALQAOAHAGANQAFAOAAAXQAAAXgEANQgGAOgLAHQgUAMhEAAg");
	this.shape_30.setTransform(-109.65,-35.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-164.3,-49,328.70000000000005,98);


(lib.Símbolo9 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFD900").s().p("ArKHGIAAglIAFAAQAlAAAAgWIgUAAIhGiSIA+AAIAsBqIAshqIA/AAIhWC1QgMAZgsAAgAJ2GUQgkAAgSgMQgZgQAAgsIAAgPQAAgpAUgQQAQgOAjAAIAoAAQAwAAASANQAVAPAAAmIAAAaIiMAAIAAAJQAAAMAJAFQAIAEASAAIASAAQAVAAAHgFQAFgEAAgIIA2AAIAAAGQAAAbgXALQgRAJgkAAgAK1EwQAAgOgIgEQgIgEgaAAQgcAAgHAEQgHAEAAAOIBUAAIAAAAgAlCGUQg/AAAAg8IAAglQAAg9A/AAIBWAAQBAAAAAA9IAAAlQAAA8hAAAgAk+EoQgJAGAAAQIAAAOQAAAQAJAHQAKAGAUAAIAOAAQAbAAAJgFQAIgFAAgPIAAgVQAAgQgIgEQgJgFgbAAIgOAAQgUAAgKAGgAHNGSIAAhYQAAgXglAAIgNAAQgnAAAAAiIAABNIg6AAIAAiZIA6AAIAAAYIAAAAQAIgPAPgGQAOgGAYAAQAnAAASAJQAdAPAAAsIAABYgADWGSIAAiZIA5AAIAACZgABuGSIAAjZIA6AAIAADZgAAKGSIAAhYQAAgXgkAAIgOAAQgnAAAAAiIAABNIg5AAIAAiZIA5AAIAAAYIABAAQAHgPAQgGQANgGAZAAQAlAAASAJQAdAPAAAsIAABYgADWDlIAAgsIA5AAIAAAsgAvnCHIAAjNIA4AAIAAAXIAAAAQAOgaAoAAIARAAQAyAAASASQAOAOAAAiIAAAaQAAAigOANQgSASgyAAIgMAAQgZAAgLgFQgLgGgKgSIAAAAIAABQgAukgYQgJAGAAARIAAAOQAAAQAJAGQAHAGASAAIAfAAQATAAAGgHQAFgFAAgPIAAgRQAAgOgFgGQgGgGgTAAIgfAAQgSAAgHAFgALwBUQgdAAgNgIQgPgKAAgZIAAgNQAAgcAVgJQAPgGAwAAQAbAAALACQAOACAIAIIAAgNQAAgMgFgEQgGgFgQAAIgiAAQgNAAgEACQgFADAAAIIg4AAQAAgeAQgKQAOgJAnAAIBDAAQA9AAAAA3IAABkIg3AAIAAgSQgMANgIADQgKAEgVAAgAL0AVQgGADAAAKQAAAIAHADQAHADAQAAIARAAQAbAAAKgEQAGgDAAgJQAAgJgFgDQgHgEgXAAIgZAAQgSAAgGAFgAG6BUQgkAAgRgMQgZgQAAgsIAAgOQAAgpATgQQARgOAjAAIBAAAQBFAAAAAzIAAAOIg4AAQAAgMgHgFQgHgEgTAAIgWAAQgkAAAAAXIAAATQAAAaAfAAIAdAAQAfAAAAgSIAAgDIA4AAIAAANQAAAdgVANQgRALgdAAgAgYBUQgkAAgRgMQgZgQAAgsIAAgOQAAgpATgQQARgOAjAAIAnAAQAvAAATANQAUAPAAAmIAAAZIiLAAIAAAJQAAAMAJAFQAIAEATAAIARAAQAVAAAHgFQAEgEAAgIIA2AAIAAAGQAAAbgWALQgSAJgkAAgAAmgPQAAgOgIgEQgIgEgZAAQgbAAgIAEQgHAEAAAOIBTAAIAAAAgAkJBUQgoAAgQgLQgRgLAAgcIA8AAQAAAHAFADQAIAEAWAAIAVAAQAUAAAHgCQAHgCAAgHQAAgHgFgDQgFgDgPAAIg2AAQgoAAgPgLQgPgMAAgeQAAgaAVgKQAPgIAjAAIAoAAQA3AAARAKQARAJAAAcIg6AAQgCgHgHgCQgIgCgZAAQgaAAgHACQgHACAAAIQAAAFAGACQAHACAVAAIAoAAQAvAAAQAPQALAJAAAZQAAAfgQAKQgQAKgxAAgAnjBUQgkAAgSgMQgZgQAAgsIAAgOQAAgpAUgQQAQgOAjAAIAoAAQAwAAASANQAVAPAAAmIAAAZIiMAAIAAAJQAAAMAJAFQAIAEASAAIASAAQAVAAAHgFQAFgEAAgIIA2AAIAAAGQAAAbgXALQgRAJgkAAgAmkgPQAAgOgIgEQgIgEgaAAQgcAAgHAEQgHAEAAAOIBUAAIAAAAgAOpBSIAAjYIA5AAIAADYgAJcBSIAAiYIA5AAIAACYgAESBSIAAhXQAAgXglAAIgOAAQgnAAAAAhIAABNIg5AAIAAiYIA5AAIAAAYIABAAQAHgPAQgGQANgGAZAAQAmAAASAJQAdAPAAAsIAABXgAryBSIAAiYIA2AAIAAAdIAAAAQAJggAvAAQAgAAANAPQAOAOAAAgIgBAMIgyAAQAAgPgFgGQgGgHgQAAQgiAAAAAaIAABUgAJchaIAAgsIA5AAIAAAsgANqjrQgyAAgSgSQgOgNAAgiIAAgbQAAgiAOgOQASgSAyAAIARAAQAvAAAFAfIAAAAIAAhcIA6AAIAADZIg2AAIAAgdIgBAAQgKAfgtAAgANVlXQgFAGAAAOIAAASQAAAPAFAFQAGAHATAAIAiAAQASAAAIgGQAJgGAAgQIAAgPQAAgRgJgGQgIgFgSAAIgiAAQgTAAgGAGgAJnjrQgdAAgNgIQgQgKAAgZIAAgNQAAgdAVgJQAQgGAwAAQAaAAALACQAPACAIAIIAAgNQAAgMgGgEQgFgFgRAAIghAAQgNAAgEACQgFADgBAIIg3AAQAAgeAQgKQAOgJAnAAIBDAAQA8AAAAA3IAABlIg2AAIAAgSQgNANgIADQgJAEgVAAgAJqkqQgFADAAAKQAAAIAGADQAHADARAAIARAAQAbAAAJgEQAHgDAAgJQAAgJgGgDQgHgEgWAAIgaAAQgRAAgHAFgAGQjrQgyAAgSgSQgOgNAAgiIAAgbQAAgiAOgOQASgSAyAAIARAAQAvAAAFAfIAAAAIAAhcIA6AAIAADZIg2AAIAAgdIgBAAQgKAfgtAAgAF7lXQgFAGAAAOIAAASQAAAPAFAFQAGAHATAAIAiAAQASAAAIgGQAJgGAAgQIAAgPQAAgRgJgGQgIgFgSAAIgiAAQgTAAgGAGgAhBjrQgdAAgNgIQgQgKAAgZIAAgNQAAgdAVgJQAQgGAwAAQAaAAALACQAOACAIAIIAAgNQAAgMgGgEQgFgFgQAAIghAAQgNAAgEACQgFADgBAIIg3AAQAAgeAQgKQAOgJAnAAIBCAAQA8AAAAA3IAABlIg2AAIAAgSQgNANgIADQgIAEgVAAgAg+kqQgFADAAAKQAAAIAGADQAHADARAAIARAAQAaAAAJgEQAHgDAAgJQAAgJgGgDQgHgEgVAAIgaAAQgRAAgHAFgAkYjrQgyAAgSgSQgOgNAAgiIAAgbQAAgiAOgOQASgSAyAAIARAAQAvAAAFAfIAAAAIAAhcIA6AAIAADZIg2AAIAAgdIgBAAQgKAfgtAAgAktlXQgFAGAAAOIAAASQAAAPAFAFQAGAHATAAIAiAAQASAAAIgGQAJgGAAgQIAAgPQAAgRgJgGQgIgFgSAAIgiAAQgTAAgGAGgAofjrQg/AAAAg8IAAglQAAg9A/AAIBWAAQA/AAAAA9IAAAlQAAA8g/AAgAoblXQgKAGAAAQIAAAOQAAAQAKAHQAJAGAVAAIANAAQAcAAAIgFQAJgFAAgPIAAgVQAAgQgJgEQgIgFgcAAIgNAAQgVAAgJAGgADejtIAAiZIA5AAIAACZgAB2jtIAAjZIA6AAIAADZgArFjtIAAicIgBAAIhXCcIgyAAIhXicIgBAAIAACcIhBAAIAAjZIBnAAIBLCLIBLiLIBmAAIAADZgADemaIAAgsIA5AAIAAAsg");
	this.shape.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100,-45.5,200.1,91.1);


(lib.Símbolo8 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AvRCmIAAlLIejAAIAAFLgAIHAuQAGAEAKAEQAMADAMAAQASAAAMgIQALgHgBgNQAAgNgJgGQgHgFgNgDIgWgDQgJgDAAgIQAAgGAGgDQAFgEAMAAQAQAAALAIIAIgOQgOgJgVAAQgTAAgKAIQgLAIAAANQAAAMAKAGQAGAFAOADIAVAEQAJADAAAHQAAANgWAAQgUAAgOgKgAGqgaQgOAOAAAUQAAAVAOAOQAOAOAWAAQAVAAAOgOQAOgOAAgVQAAgUgOgOQgOgOgVAAQgWAAgOAOgAFHgaQgPAOAAAUQAAAVAPAOQANAOAXAAQAaAAAMgVIgNgIQgIAOgSAAQgOAAgJgJQgKgKAAgPQAAgOAKgJQAJgJAOAAQASAAAIANIANgIQgLgVgbAAQgXAAgNAOgABDgaQgPAOAAAUQAAAVAPAOQAOAOAWAAQAbAAAMgVIgNgIQgJAOgRAAQgOAAgKgJQgJgKAAgPQAAgOAJgJQAKgJAOAAQARAAAJANIANgIQgMgVgbAAQgWAAgOAOgAgrgaQgOAOAAAUQABAWAOANQAOAOAXAAQAXAAANgQIgJgLQgKAMgQAAQgPAAgJgIQgJgIgCgMIBMAAIABgFQAAgVgOgOQgNgOgUAAQgUAAgOAOgAh5gYIAQAAIAAAzQAAAOAIAIQAHAIAPAAQANAAAIgHIgFgMQgGAEgIAAQgPAAAAgQIAAgyIAcAAIAAgPIgcAAIAAgVIgRAAIAAAVIgQAAgAjUgaQgOAOgBAUQABAVAOAOQAOAOAVAAQAWAAAOgOQAOgOgBgVQABgUgOgOQgOgOgWAAQgVAAgOAOgAk4gaQgPAOAAAUQAAAVAPAOQAOAOAWAAQAbAAAMgVIgNgIQgJAOgRAAQgOAAgKgJQgJgKAAgPQAAgOAJgJQAKgJAOAAQARAAAJANIANgIQgMgVgbAAQgWAAgOAOgAnfAuQAGAEAKAEQAMADAMAAQASAAAMgIQALgHgBgNQAAgNgJgGQgHgFgNgDIgWgDQgJgDAAgIQAAgGAFgDQAGgEAMAAQAQAAALAIIAIgOQgOgJgVAAQgTAAgKAIQgLAIAAANQAAAMAKAGQAGAFAOADIAVAEQAJADAAAHQAAANgWAAQgUAAgOgKgAEQA4IARAAIAAhfIgRAAgADrADIAAA1IARAAIAAg3QAAgUgLgKQgLgLgSAAQgXAAgLAQIAAgPIgRAAIAABfIARAAIAAgxQAAgPAJgIQAIgIAOAAQAaAAAAAbgAlvA4IARAAIAAhfIgRAAgApTA4IASAAIAAgmIAgAAQAYAAAOgMQAOgLAAgUQAAgVgOgMQgOgLgYAAIgyAAgAgWg0IAQAAIAdgYIgVAAgAEQhMQgEADAAAFQAAAFAEADQADADAFAAQAFAAAEgDQADgEAAgEQAAgFgDgDQgEgDgFAAQgFAAgDADgAlvhMQgDADAAAFQAAAFADADQADADAGAAQAFAAADgDQADgEAAgEQAAgFgDgDQgDgDgFAAQgGAAgDADgAG3AhQgKgKAAgPQAAgOAKgJQAIgJAPAAQAOAAAIAJQAKAJAAAOQAAAPgKAKQgIAJgOAAQgPAAgIgJgAjIAhQgJgKAAgPQAAgOAJgJQAJgJAOAAQAOAAAJAJQAJAJAAAOQAAAPgJAKQgJAJgOAAQgOAAgJgJgApBACIAAg4IAfAAQAjAAAAAdQAAAbgjAAgAgnABQABgLAIgHQAJgIAMAAQAMAAAJAIQAHAHACALg");
	this.shape.setTransform(0,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#051744").s().p("AIVBCQgKgEgGgFIAHgNQAOAKAUAAQAWAAAAgOQAAgGgJgEIgVgDQgOgDgGgFQgKgGAAgNQAAgMALgIQAKgIATAAQAVAAAOAJIgIANQgLgHgQAAQgMAAgFAEQgGADAAAGQAAAHAJADIAWAEQANADAHAEQAJAHAAAMQABANgLAIQgMAIgSgBQgMAAgMgCgAGoA3QgOgOAAgVQAAgUAOgOQAOgOAWAAQAVAAAOAOQAOAOAAAUQAAAVgOAOQgOANgVAAQgWAAgOgNgAG1gEQgKAJAAAPQAAAPAKAKQAIAIAPABQAOgBAIgIQAKgKAAgPQAAgPgKgJQgIgIgOgBQgPABgIAIgAFFA3QgPgOAAgVQAAgUAPgOQANgOAXAAQAbAAALAVIgNAHQgIgNgSAAQgOABgJAIQgKAJAAAPQAAAPAKAKQAJAIAOABQASAAAIgOIANAIQgMAUgaAAQgXAAgNgNgABBA3QgPgOAAgVQAAgUAPgOQAOgOAWAAQAbAAAMAVIgNAHQgJgNgRAAQgOABgKAIQgJAJAAAPQAAAPAJAKQAKAIAOABQARAAAJgOIANAIQgMAUgbAAQgWAAgOgNgAgsA3QgOgOgBgVQAAgUAOgOQAOgOAUAAQAUAAANAOQAOANAAAVIgBAGIhMAAQACAMAJAIQAJAIAPAAQAQAAAKgMIAJALQgNAPgXAAQgXAAgOgNgAgggGQgIAHgBAMIA8AAQgCgMgHgHQgJgHgMAAQgMAAgJAHgAhjA9QgIgIAAgOIAAg0IgQAAIAAgOIAQAAIAAgVIARAAIAAAVIAcAAIAAAOIgcAAIAAAzQAAAQAPAAQAIAAAGgFIAFANQgIAHgNgBQgPABgHgIgAjWA3QgOgOgBgVQABgUAOgOQAOgOAVAAQAWAAAOAOQAOAOgBAUQABAVgOAOQgOANgWAAQgVAAgOgNgAjKgEQgJAJAAAPQAAAPAJAKQAJAIAOABQAOgBAJgIQAJgKAAgPQAAgPgJgJQgJgIgOgBQgOABgJAIgAk6A3QgPgOAAgVQAAgUAPgOQAOgOAWAAQAbAAAMAVIgNAHQgJgNgRAAQgOABgKAIQgJAJAAAPQAAAPAJAKQAKAIAOABQARAAAJgOIANAIQgMAUgbAAQgWAAgOgNgAnRBCQgKgEgGgFIAHgNQAOAKAUAAQAWAAAAgOQAAgGgJgEIgVgDQgOgDgGgFQgKgGAAgNQAAgMALgIQAKgIATAAQAVAAAOAJIgIANQgLgHgQAAQgMAAgGAEQgFADAAAGQAAAHAJADIAWAEQANADAHAEQAJAHAAAMQABANgLAIQgMAIgSgBQgMAAgMgCgAEOBDIAAheIARAAIAABegADpBDIAAg1QAAgbgaAAQgOABgIAHQgJAIAAAQIAAAwIgRAAIAAheIARAAIAAAOQALgPAXAAQASAAALALQALAKAAATIAAA3gAlxBDIAAheIARAAIAABegApVBDIAAh9IAyAAQAYAAAOAMQAOAMAAAUQAAAUgOAMQgOAMgYgBIggAAIAAAmgApDANIAfAAQAjAAAAgbQAAgcgjAAIgfAAgAgYgpIAYgXIAVAAIgdAXgAEOgxQgEgCAAgGQAAgEAEgEQADgDAFAAQAFAAAEADQADAEAAAEQAAAFgDADQgEAEgFAAQgFAAgDgEgAlxgxQgDgCAAgGQAAgEADgEQADgDAGAAQAFAAADADQADAEAAAEQAAAFgDADQgDAEgFAAQgGAAgDgEg");
	this.shape_1.setTransform(0.2,-1.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-97.8,-16.5,195.7,33.1);


(lib.Símbolo7 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AvRCmIAAlLIejAAIAAFLgAMOAtQAHAFAKADQALADAMAAQATAAALgHQALgIAAgNQAAgMgKgHQgGgEgOgDIgVgDQgJgEAAgHQgBgGAGgEQAGgDALAAQAQAAALAHIAIgNQgOgJgVAAQgSAAgLAIQgKAIAAANQAAALAJAHQAHAFANACIAVAEQAJAEAAAGQAAANgWAAQgUAAgOgJgAKxgaQgNANAAAVQAAAVANAOQAOANAWAAQAWAAANgNQAPgOAAgVQAAgVgPgNQgNgOgWAAQgWAAgOAOgAI8AtQAHAFAKADQALADAMAAQATAAALgHQALgIAAgNQAAgMgKgHQgGgEgOgDIgVgDQgKgEAAgHQAAgGAGgEQAGgDALAAQAQAAAMAHIAHgNQgNgJgWAAQgSAAgLAIQgLAIAAANQAAALAKAHQAGAFAPACIAUAEQAKAEgBAGQABANgXAAQgTAAgOgJgAFngaQgNANAAAVQgBAVAOAOQAPANAXAAQAYAAAOgPIgKgLQgLALgQAAQgPAAgJgHQgKgIgBgNIBNAAIAAgFQAAgVgMgNQgOgOgVAAQgUAAgOAOgAEEgaQgOANAAAVQAAAVAOAOQAOANAWAAQAbAAAMgUIgOgIQgIANgSAAQgOAAgIgJQgKgJAAgPQAAgPAKgJQAIgJAOAAQASAAAIAOIAOgJQgMgUgbAAQgWAAgOAOgACOAtQAHAFAKADQALADAMAAQATAAALgHQALgIAAgNQAAgMgKgHQgGgEgOgDIgVgDQgKgEABgHQgBgGAGgEQAGgDALAAQAQAAALAHIAIgNQgOgJgVAAQgSAAgLAIQgKAIAAANQAAALAJAHQAHAFANACIAVAEQAJAEAAAGQAAANgWAAQgTAAgPgJgAAlAcQAAANAKAHQAJAIARAAQAVAAAJgNIAAAMIARAAIAAg4QAAgngpAAQgYAAgPAMIAHANQAMgKASAAQAZAAABAXIAAACIgbAAQgnAAAAAcgAh/AtQAHAFAKADQALADAMAAQATAAALgHQALgIAAgNQAAgMgKgHQgGgEgOgDIgVgDQgKgEABgHQgBgGAGgEQAGgDALAAQAQAAALAHIAIgNQgOgJgVAAQgSAAgLAIQgKAIAAANQAAALAJAHQAHAFANACIAVAEQAJAEAAAGQAAANgWAAQgTAAgPgJgAjcgaQgOANAAAVQAAAVAOAOQAPANAVAAQAWAAAOgNQANgOAAgVQAAgVgNgNQgOgOgWAAQgVAAgPAOgAm+AtQAGAFALADQAKADAMAAQAUAAALgHQAKgIABgNQAAgMgKgHQgHgEgOgDIgVgDQgJgEAAgHQAAgGAGgEQAFgDAMAAQAPAAAMAHIAHgNQgNgJgVAAQgTAAgLAIQgKAIAAANQAAALAJAHQAHAFAOACIAVAEQAJAEAAAGQAAANgXAAQgTAAgOgJgAobgaQgOANAAAVQAAAVAOAOQAOANAVAAQAXAAANgNQAOgOAAgVQAAgVgOgNQgNgOgXAAQgVAAgOAOgAqKgbQgNAOAAAVQAAAVANAOQAOANAVAAQAXAAAMgQIAAAPIAQAAIAAiEIgRAAIAAA0QgMgPgWAAQgVAAgOANgAr3gaQgOANAAAVQAAAVAOAOQAOANAVAAQAXAAANgNQAOgOAAgVQAAgVgOgNQgNgOgXAAQgVAAgOAOgAIZACIAAA1IASAAIAAg3QAAgTgLgLQgKgKgSAAQgYAAgLAPIAAgOIgRAAIAABeIARAAIAAgxQABgOAIgJQAIgIAOAAQAaAAgBAbgAkSA3IARAAIAAiEIgRAAgAtbg2IArAAIAABtIASAAIAAhtIArAAIAAgQIhoAAgAA7AnQgFgEAAgHQAAgPAWAAIAbAAIAAANQgHARgVAAQgJAAgHgEgAK/AgQgKgJAAgPQAAgPAKgJQAIgJAOAAQAOAAAJAJQAKAJAAAPQAAAPgKAJQgJAJgOAAQgOAAgIgJgAjPAgQgJgJAAgPQAAgPAJgJQAJgJAOAAQAOAAAJAJQAKAJAAAPQAAAPgKAJQgJAJgOAAQgOAAgJgJgAoOAgQgJgJAAgPQAAgPAJgJQAIgJAOAAQAOAAAJAJQAKAJAAAPQAAAPgKAJQgJAJgOAAQgOAAgIgJgAp8AgQgJgJAAgPQAAgPAJgJQAJgJANAAQAOAAAKAJQAJAJAAAPQAAAPgJAJQgKAJgOAAQgNAAgJgJgArqAgQgKgJAAgPQAAgPAKgJQAJgJANAAQAOAAAKAJQAJAJAAAPQAAAPgJAJQgKAJgOAAQgNAAgJgJgAFrABQABgLAJgIQAIgHAMAAQANAAAJAHQAHAIACALg");
	this.shape.setTransform(0,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#051744").s().p("AMeBAQgLgDgGgFIAHgNQAOAJAUAAQAWAAAAgNQAAgGgJgEIgVgEQgOgCgGgFQgKgHAAgLQAAgNALgIQALgIASAAQAVAAAOAJIgIANQgLgHgQAAQgLAAgGADQgGAEAAAGQAAAGAKAEIAVAEQAOADAGAEQAKAHAAAMQAAANgLAIQgLAHgTAAQgMAAgLgDgAKwA2QgOgOAAgVQAAgVAOgNQAOgOAWAAQAWAAANAOQAOANAAAVQAAAVgOAOQgNANgWAAQgWAAgOgNgAK9gFQgJAIAAAQQAAAPAJAJQAJAJAOAAQAOAAAJgJQAJgJAAgPQAAgQgJgIQgJgJgOAAQgOAAgJAJgAJMBAQgLgDgGgFIAHgNQAOAJAUAAQAWAAAAgNQAAgGgJgEIgVgEQgOgCgGgFQgKgHAAgLQAAgNALgIQALgIASAAQAVAAAOAJIgIANQgLgHgQAAQgLAAgGADQgGAEAAAGQAAAGAKAEIAVAEQAOADAGAEQAKAHAAAMQAAANgLAIQgLAHgTAAQgMAAgLgDgAFmA2QgOgOAAgVQAAgVAOgNQANgOAVAAQAVAAANAOQANANAAAVIAAAFIhNAAQABANAKAIQAJAHAOAAQARAAALgLIAJALQgNAPgYAAQgXAAgPgNgAFzgHQgIAHgBAMIA9AAQgCgMgIgHQgIgHgNAAQgMAAgJAHgAEDA2QgPgOAAgVQAAgVAPgNQAOgOAWAAQAbAAAMAUIgOAJQgIgOgSAAQgOAAgJAJQgJAIAAAQQAAAPAJAJQAJAJAOAAQASAAAIgNIAOAIQgMAUgbAAQgWAAgOgNgACeBAQgLgDgGgFIAHgNQAOAJAUAAQAWAAAAgNQAAgGgJgEIgVgEQgOgCgGgFQgKgHAAgLQAAgNALgIQALgIASAAQAVAAAOAJIgIANQgLgHgQAAQgLAAgGADQgGAEAAAGQAAAGAKAEIAVAEQAOADAGAEQAKAHAAAMQAAANgLAIQgLAHgTAAQgMAAgLgDgAAtA7QgJgHAAgNQAAgcAmAAIAbAAIAAgDQAAgWgZAAQgSAAgMAKIgIgNQAQgMAYAAQApAAAAAmIAAA5IgRAAIAAgMQgJANgWAAQgQAAgKgIgAA1AnQAAAHAFAEQAGAEAKAAQAVAAAGgRIAAgNIgaAAQgWAAAAAPgAhvBAQgLgDgGgFIAHgNQAOAJAUAAQAWAAAAgNQAAgGgJgEIgVgEQgOgCgGgFQgKgHAAgLQAAgNALgIQALgIASAAQAVAAAOAJIgIANQgLgHgQAAQgLAAgGADQgGAEAAAGQAAAGAKAEIAVAEQAOADAGAEQAKAHAAAMQAAANgLAIQgLAHgTAAQgMAAgLgDgAjdA2QgOgOAAgVQAAgVAOgNQAOgOAWAAQAWAAANAOQAOANAAAVQAAAVgOAOQgNANgWAAQgWAAgOgNgAjQgFQgJAIAAAQQAAAPAJAJQAJAJAOAAQAOAAAJgJQAJgJAAgPQAAgQgJgIQgJgJgOAAQgOAAgJAJgAmvBAQgKgDgGgFIAHgNQAOAJATAAQAXAAAAgNQAAgGgJgEIgVgEQgOgCgHgFQgJgHAAgLQAAgNAKgIQALgIASAAQAWAAANAJIgHANQgMgHgQAAQgLAAgGADQgFAEAAAGQAAAGAJAEIAVAEQAOADAHAEQAJAHAAAMQAAANgLAIQgLAHgTAAQgMAAgLgDgAocA2QgOgOAAgVQAAgVAOgNQAOgOAVAAQAWAAAOAOQAOANAAAVQAAAVgOAOQgOANgWAAQgVAAgOgNgAoPgFQgKAIAAAQQAAAPAKAJQAIAJAOAAQAOAAAJgJQAKgJAAgPQAAgQgKgIQgJgJgOAAQgOAAgIAJgAqLA2QgNgOAAgVQAAgVANgOQAOgNAVAAQAWAAALAPIAAg0IASAAIAACEIgRAAIAAgPQgMAQgWAAQgVAAgOgNgAp9gFQgKAIAAAQQAAAPAKAJQAIAJAOAAQAOAAAJgJQAKgJAAgPQAAgQgKgIQgJgJgOAAQgOAAgIAJgAr4A2QgOgOAAgVQAAgVAOgNQAOgOAVAAQAWAAAOAOQAOANAAAVQAAAVgOAOQgOANgWAAQgVAAgOgNgArrgFQgKAIAAAQQAAAPAKAJQAIAJAOAAQAOAAAJgJQAKgJAAgPQAAgQgKgIQgJgJgOAAQgOAAgIAJgAIYBCIAAg1QAAgbgZAAQgOAAgIAIQgJAIAAAPIAAAxIgRAAIAAheIARAAIAAAOQALgPAXAAQASAAALAKQALALAAATIAAA3gAkTBCIAAiEIARAAIAACEgAsxBCIAAhtIgsAAIAAgQIBpAAIAAAQIgsAAIAABtg");
	this.shape_1.setTransform(0.125,-1.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-97.8,-16.5,195.7,33.1);


(lib.Símbolo6 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AvRCmIAAlLIejAAIAAFLgAAhBTQAIAGANAAQAOAAAJgJQAIgIAAgPIAAhjIgRAAIAABjQgBARgOAAQgIAAgGgEgAJ+AaQAAAMAJAIQAKAIAQAAQAWAAAKgOIAAANIAQAAIAAg5QAAgngpAAQgYAAgPANIAHANQAMgLASAAQAaAAAAAXIAAAEIgbAAQgnAAAAAbgAGmgbIAQAAIAAAzQABAOAHAIQAIAIAPAAQANAAAIgHIgGgMQgGAEgHAAQgPAAgBgQIAAgyIAcAAIAAgPIgcAAIAAgVIgRAAIAAAVIgQAAgAFFAMQAAAVALALQALAKATAAQAVAAAMgQIAAAPIAQAAIAAhfIgRAAIAAAxQgBAPgHAIQgJAIgNAAQgZAAAAgcIAAg0IgSAAgADngdQgOAOAAAUQAAAVAOAOQAPAOAVAAQAcAAAMgVIgOgIQgJAOgRAAQgOAAgJgJQgKgKABgPQgBgOAKgJQAJgJAOAAQARAAAJANIAOgIQgMgVgcAAQgVAAgPAOgAB5gdQgOAOAAAUQAAAWAOANQAPAOAWAAQAZAAANgQIgKgLQgKAMgRAAQgOAAgJgIQgKgIgCgMIBOAAIAAgFQAAgVgNgOQgNgOgVAAQgVAAgNAOgAjwAaQAAAMAKAIQAJAIARAAQAVAAAJgOIAAANIARAAIAAg5QAAgngpAAQgYAAgQANIAIANQAMgLASAAQAaAAgBAXIAAAEIgbAAQgmAAAAAbgAmQAaQAAAMAKAIQAJAIARAAQAWAAAJgOIAAANIAQAAIAAg5QABgngpAAQgZAAgPANIAHANQANgLARAAQAaAAAAAXIAAAEIgbAAQgnAAAAAbgAnngdQgOAOAAAUQAAAVAOAOQAPAOAVAAQAbAAANgVIgOgIQgJAOgRAAQgOAAgJgJQgJgKAAgPQAAgOAJgJQAJgJAOAAQARAAAJANIAOgIQgMgVgcAAQgVAAgPAOgApcArQAGAEAKAEQAMADAMAAQASAAALgIQAMgHgBgNQAAgNgJgGQgHgFgNgCIgVgEQgKgDAAgIQAAgGAFgDQAHgEAKAAQAQAAAMAIIAIgOQgOgJgWAAQgRAAgLAIQgLAIAAANQAAANAKAFQAGAFAOADIAVAEQAJADAAAHQAAANgWAAQgUAAgOgKgAI7A1IARAAIAqhfIgRAAIghBMIgihMIgSAAgAHwA1IARAAIAAhfIgRAAgAg8A1IBbAAIAAgQIhJAAIAAgoIA+AAIAAgPIg+AAIAAgnIBGAAIAAgPIhYAAgAkaA1IARAAIAAiFIgRAAgArQA1IBcAAIAAgQIhKAAIAAgoIA/AAIAAgPIg/AAIAAgnIBHAAIAAgPIhZAAgAHwhPQgDADAAAFQAAAFADADQADADAGAAQAFAAADgDQADgEAAgEQAAgFgDgDQgDgDgFAAQgGAAgDADgABEhPQgEADAAAFQAAAFAEADQADADAFAAQAFAAAEgDQACgEAAgEQAAgFgCgDQgEgDgFAAQgFAAgDADgAKVAkQgGgEAAgHQAAgPAWAAIAbAAIAAAOQgHARgVAAQgKAAgFgFgAjaAkQgFgEAAgHQAAgPAWAAIAaAAIAAAOQgGARgVAAQgJAAgHgFgAl5AkQgFgEAAgHQAAgPAVAAIAbAAIAAAOQgHARgVAAQgJAAgGgFgAB8gBQABgMAJgHQAJgIAMAAQAMAAAJAIQAIAHABAMg");
	this.shape.setTransform(0,-0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#051744").s().p("AAhBQIAGgNQAFAFAJgBQAOABAAgSIAAhjIARAAIAABjQAAAPgIAJQgIAIgOAAQgOAAgHgGgAKHArQgJgIAAgMQAAgbAmAAIAbAAIAAgEQAAgWgZAAQgSAAgMAKIgIgNQAQgNAYAAQApABAAAmIAAA5IgRAAIAAgNQgJAOgWAAQgQAAgKgIgAKPAXQAAAGAFAEQAGAFAKAAQAVAAAGgRIAAgOIgaAAQgWABAAAPgAG+ArQgIgHAAgPIAAgzIgQAAIAAgPIAQAAIAAgUIARAAIAAAUIAcAAIAAAPIgcAAIAAAzQAAAPAPAAQAIABAGgFIAFAMQgHAHgOAAQgOAAgIgIgAFQApQgLgLAAgVIAAg2IARAAIAAA0QAAAcAaAAQANABAIgJQAIgIAAgPIAAgxIASAAIAABfIgRAAIAAgPQgLAQgVAAQgTAAgLgKgADnAlQgOgOAAgUQAAgVAOgNQAOgOAWgBQAcAAALAVIgNAIQgJgNgRAAQgOAAgJAJQgKAJAAAPQAAAPAKAJQAJAJAOAAQARAAAJgNIANAIQgMAUgbAAQgWAAgOgOgAB5AlQgOgNAAgVQAAgVANgNQAOgOAVgBQAUABAOAOQANANAAAVIgBAFIhNAAQACANAJAHQAKAIAOAAQARAAAKgLIAKAKQgOAQgYAAQgXAAgOgOgACGgXQgJAIgBAMIA9AAQgBgMgIgIQgJgHgMAAQgNAAgIAHgAjnArQgJgIAAgMQAAgbAmAAIAbAAIAAgEQAAgWgZAAQgSAAgMAKIgIgNQAQgNAYAAQApABAAAmIAAA5IgRAAIAAgNQgJAOgWAAQgQAAgKgIgAjfAXQAAAGAFAEQAGAFAKAAQAVAAAGgRIAAgOIgaAAQgWABAAAPgAmGArQgKgIAAgMQAAgbAnAAIAbAAIAAgEQAAgWgaAAQgSAAgMAKIgHgNQAPgNAYAAQApABAAAmIAAA5IgQAAIAAgNQgJAOgWAAQgRAAgJgIgAl/AXQAAAGAGAEQAGAFAJAAQAVAAAHgRIAAgOIgbAAQgWABAAAPgAnnAlQgOgOAAgUQAAgVAOgNQAOgOAWgBQAcAAALAVIgNAIQgJgNgRAAQgOAAgJAJQgKAJAAAPQAAAPAKAJQAJAJAOAAQARAAAJgNIANAIQgMAUgbAAQgWAAgOgOgApMAwQgKgDgGgFIAHgOQAOAKATAAQAXAAAAgNQAAgHgJgDIgVgEQgOgCgHgGQgJgFAAgNQAAgMAKgJQALgIASAAQAWAAANAJIgHAOQgMgHgQAAQgLgBgGAEQgFAEAAAFQAAAIAJADIAVAFQAOACAHAEQAJAHAAAMQAAANgLAHQgLAIgTAAQgMAAgLgDgAI6AyIgqhfIASAAIAhBMIAihMIARAAIgqBfgAHwAyIAAhfIARAAIAABfgAg8AyIAAh9IBYAAIAAAQIhGAAIAAAnIA+AAIAAAPIg+AAIAAAnIBIAAIAAAQgAkaAyIAAiFIARAAIAACFgArQAyIAAh9IBZAAIAAAQIhHAAIAAAnIA/AAIAAAPIg/AAIAAAnIBKAAIAAAQgAHwhCQgDgDAAgFQAAgEADgEQADgDAFAAQAFAAAEADQADADAAAFQAAAFgDADQgEAEgFgBQgFABgDgEgABDhCQgDgDAAgFQAAgEADgEQAEgDAFAAQAFAAADADQADADAAAFQAAAFgDADQgDAEgFgBQgFABgEgEg");
	this.shape_1.setTransform(0.025,0.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-97.8,-16.6,195.7,33.2);


(lib.Símbolo5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AvRCmIAAlLIejAAIAAFLgAIQAfQAAANAKAHQAJAIARAAQAWAAAJgNIAAAMIAQAAIAAg5QAAgmgoAAQgZAAgPAMIAHANQAMgKATAAQAZAAAAAWIAAADIgbAAQgnAAAAAcgAG6gXQgPANAAAVQAAAVAPAOQAOANAWAAQAbAAAMgUIgOgIQgJANgRAAQgOAAgJgJQgJgJAAgPQAAgPAJgJQAJgJAOAAQARAAAJAOIAOgJQgMgUgbAAQgWAAgOAOgAESAwQAHAFAKADQALADAMAAQATAAALgHQALgIAAgNQAAgMgJgHQgHgEgOgDIgVgEQgKgDAAgHQABgGAFgEQAGgDALAAQAQAAAMAHIAHgNQgNgJgWAAQgSAAgLAIQgLAIAAANQAAALAKAHQAGAFAPACIAUAEQAKAEAAAGQAAANgXAAQgTAAgOgJgACpAfQAAANAJAHQAKAIAQAAQAXAAAJgNIAAAMIAQAAIAAg5QAAgmgpAAQgYAAgPAMIAHANQAMgKASAAQAaAAAAAWIAAADIgbAAQgnAAAAAcgAiCAfQAAANAJAHQAKAIARAAQAWAAAIgNIAAAMIARAAIAAg5QAAgmgpAAQgYAAgQAMIAIANQAMgKASAAQAaAAgBAWIAAADIgbAAQgmAAAAAcgAkiAfQAAANAKAHQAJAIARAAQAWAAAJgNIAAAMIAQAAIAAg5QAAgmgoAAQgZAAgPAMIAHANQAMgKATAAQAZAAAAAWIAAADIgbAAQgnAAAAAcgAl4gXQgPANAAAVQAAAVAPAOQAOANAWAAQAbAAAMgUIgOgIQgJANgRAAQgOAAgJgJQgJgJAAgPQAAgPAJgJQAJgJAOAAQARAAAJAOIAOgJQgMgUgbAAQgWAAgOAOgAnuAwQAGAFAKADQALADANAAQASAAALgHQALgIAAgNQABgMgKgHQgHgEgOgDIgUgEQgKgDAAgHQAAgGAFgEQAGgDALAAQAQAAAMAHIAHgNQgNgJgWAAQgRAAgMAIQgKAIAAANQAAALAKAHQAGAFAOACIAVAEQAJAEAAAGQAAANgXAAQgTAAgOgJgAGCA6IARAAIAAheIgRAAgAAxA6IA8AAQAYAAAMgJQAMgIABgRQgBgYgYgGQASgIgBgUQAAgQgLgIQgMgJgWAAIg4AAgAisA6IARAAIAAiEIgRAAgAphA6IBbAAIAAgPIhJAAIAAgpIA/AAIAAgOIg/AAIAAgnIBHAAIAAgQIhZAAgADHgyIAQAAIAfgXIgXAAgAGChKQgDAEAAAEQAAAFADADQAEAEAFAAQAFAAADgEQAEgDAAgFQAAgFgEgDQgDgDgFAAQgFAAgEADgAInAqQgFgEgBgHQAAgPAXAAIAaAAIAAANQgGARgWAAQgJAAgGgEgADAAqQgGgEAAgHQAAgPAWAAIAbAAIAAANQgHARgVAAQgKAAgFgEgAhsAqQgFgEAAgHQAAgPAWAAIAaAAIAAANQgGARgVAAQgJAAgHgEgAkLAqQgFgEgBgHQAAgPAXAAIAaAAIAAANQgGARgWAAQgJAAgGgEgABDAsIAAgqIAqAAQAeAAAAAVQAAAVgeAAgABDgMIAAgoIAlAAQAdAAgBAUQABAUgdAAg");
	this.shape.setTransform(0,-0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#051744").s().p("AIaA9QgKgIAAgNQAAgcAnAAIAaAAIAAgDQABgWgaAAQgSAAgMALIgIgOQAQgMAYAAQApAAAAAmIAAA5IgRAAIAAgMQgJAOgVAAQgRgBgJgHgAIhAoQAAAHAFAEQAHAEAJAAQAVAAAGgRIAAgNIgaAAQgWAAAAAPgAG5A3QgPgOAAgVQAAgVAPgNQAOgOAWAAQAcAAALAUIgNAIQgJgNgRAAQgOABgKAIQgJAJAAAPQAAAPAJAKQAKAJAOAAQARAAAJgOIANAIQgMAUgbABQgWAAgOgOgAEiBBQgKgDgGgFIAHgNQAOAKAUAAQAWgBAAgNQAAgGgJgEIgVgDQgOgDgGgFQgKgHAAgMQAAgMAKgIQAMgIARAAQAWAAANAJIgHANQgMgHgQAAQgLAAgGAEQgFADAAAGQAAAGAKAEIAUAEQAOADAHAEQAKAHgBAMQAAAOgLAHQgLAIgSAAQgNgBgLgDgACyA9QgJgIAAgNQAAgcAmAAIAbAAIAAgDQAAgWgaAAQgRAAgMALIgIgOQAQgMAXAAQApAAAAAmIAAA5IgQAAIAAgMQgJAOgWAAQgQgBgKgHgAC6AoQgBAHAGAEQAGAEAJAAQAWAAAGgRIAAgNIgbAAQgWAAABAPgAh5A9QgKgIAAgNQAAgcAnAAIAbAAIAAgDQAAgWgZAAQgTAAgLALIgIgOQAPgMAYAAQAqAAAAAmIAAA5IgRAAIAAgMQgJAOgWAAQgQgBgKgHgAhyAoQAAAHAGAEQAGAEAKAAQAUAAAHgRIAAgNIgaAAQgXAAAAAPgAkYA9QgKgIAAgNQAAgcAmAAIAbAAIAAgDQABgWgaAAQgSAAgMALIgIgOQAQgMAYAAQApAAAAAmIAAA5IgRAAIAAgMQgJAOgVAAQgRgBgJgHgAkRAoQAAAHAFAEQAHAEAJAAQAVAAAGgRIAAgNIgaAAQgWAAAAAPgAl5A3QgPgOAAgVQAAgVAPgNQAOgOAWAAQAcAAALAUIgNAIQgJgNgSAAQgNABgKAIQgJAJAAAPQAAAPAJAKQAKAJANAAQASAAAJgOIANAIQgMAUgbABQgWAAgOgOgAneBBQgKgDgHgFIAIgNQAOAKATAAQAXgBgBgNQABgGgKgEIgUgDQgPgDgGgFQgKgHAAgMQAAgMALgIQALgIASAAQAWAAANAJIgHANQgMgHgQAAQgLAAgGAEQgFADgBAGQAAAGAKAEIAVAEQAOADAHAEQAJAHAAAMQAAAOgLAHQgLAIgTAAQgMgBgLgDgAGCBDIAAheIARAAIAABegAAwBDIAAh9IA5AAQAWAAALAJQAMAIAAAQQAAAUgRAHQAYAGAAAaQAAAQgNAIQgMAJgYAAgABCA1IAqAAQAeAAAAgVQAAgVgeAAIgqAAgABCgCIAmAAQAcAAAAgVQAAgUgcAAIgmAAgAisBDIAAiEIARAAIAACEgApiBDIAAh9IBZAAIAAAQIhHAAIAAAnIA/AAIAAAOIg/AAIAAApIBJAAIAAAPgADGgpIAZgXIAWAAIgeAXgAGCgxQgDgDAAgEQAAgFADgDQAEgEAFAAQAEAAAEAEQADACAAAGQAAAEgDADQgEAEgEAAQgFAAgEgEg");
	this.shape_1.setTransform(0.05,-0.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-97.8,-16.6,195.7,33.2);


(lib.Símbolo3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FED800").s().p("AmDGcIAAi6IAyAAIAAAVIAAAAQAMgXAlAAIAPAAQAtAAAQAQQANAMAAAfIAAAYQAAAfgNAMQgQAQgtAAIgLAAQgWAAgKgFQgLgFgIgQIgBAAIAABIgAlIEMQgIAFAAAPIAAAOQAAAOAIAGQAHAFARAAIAbAAQARAAAGgGQAEgFAAgNIAAgQQAAgNgEgFQgGgGgRAAIgbAAQgRAAgHAFgADfFnQgOgJAAgXIAAgMQAAgaAUgIQAOgFArAAQAYAAAJABQAOADAHAHIAAgMQAAgLgFgEQgFgEgPAAIgeAAQgMAAgEACQgEACAAAHIgyAAQAAgaAOgJQANgIAjAAIA8AAQA2AAAAAxIAABbIgxAAIAAgQQgLAMgHADQgIADgTAAIgkAAIgDAAQgYAAgLgHgAEJE1QgFADAAAJQAAAHAGADQAGADAPAAIAPAAQAYAAAJgEQAGgDAAgIQAAgIgFgDQgHgDgUAAIgXAAQgQAAgFAEgAiiFnQgOgJAAgXIAAgMQAAgaATgIQAOgFArAAQAYAAAKABQANADAHAHIAAgMQAAgLgFgEQgFgEgOAAIgfAAQgLAAgEACQgEACgBAHIgyAAQAAgaAPgJQAMgIAjAAIA8AAQA2AAAAAxIAABbIgwAAIAAgQQgLAMgIADQgIADgTAAIgjAAIgDAAQgYAAgLgHgAh5E1QgFADAAAJQAAAHAGADQAGADAPAAIAPAAQAZAAAIgEQAGgDAAgIQAAgIgFgDQgGgDgUAAIgXAAQgQAAgGAEgAAmFsIAAiKIAxAAIAAAaIAAAAQAIgcArAAQAcAAAMANQAMAMAAAdIAAAMIgtAAQAAgOgFgFQgFgHgPAAQgeAAAAAYIAABMgAogB6IAAi5IAyAAIAAAVIABAAQAMgXAkAAIAPAAQAuAAAQAQQAMAMAAAfIAAAXQAAAfgMAMQgQAQguAAIgKAAQgXAAgKgFQgKgFgJgQIAAAAIAABIgAnkgVQgIAFAAAPIAAANQAAAOAIAGQAHAFAQAAIAcAAQARAAAFgGQAFgFAAgNIAAgPQAAgNgFgFQgFgGgRAAIgcAAQgQAAgHAFgASxBMQgkAAgOgKQgPgKAAgZIA1AAQAAAGAFADQAHAEAUAAIATAAQASAAAGgCQAHgDAAgGQAAgGgFgCQgEgDgOAAIgwAAQglAAgNgKQgNgKAAgcQAAgXASgJQAOgHAfAAIAkAAQAyAAAQAJQAOAIABAZIg0AAQgCgGgHgCQgHgCgXAAQgXAAgGACQgHACAAAHQAAAEAGACQAGACATAAIAkAAQArAAAOANQAKAIAAAXQAAAbgPAKQgOAJgtAAgAPtBMQggAAgQgLQgWgPAAgnIAAgNQAAgkARgPQAPgMAfAAIAlAAQAqAAARAMQASANAAAiIAAAXIh+AAIAAAIQAAAKAIAFQAHAEARAAIAQAAQATAAAGgFQAFgDAAgIIAwAAIAAAGQAAAYgUAKQgQAIggAAgAQmgNQAAgMgIgEQgHgEgXAAQgZAAgGAEQgHADAAANIBMAAIAAAAgAIrBMQg5AAAAg3IAAggQAAg2A5AAIBNAAQA5AAAAA2IAAAgQAAA3g5AAgAIugVQgJAGAAAOIAAAMQAAAPAJAGQAIAFATAAIAMAAQAZAAAIgEQAHgFAAgOIAAgSQAAgNgHgFQgIgEgZAAIgMAAQgTAAgIAFgAEKBMQghAAgPgLQgXgPAAgnIAAgNQAAgkASgPQAOgMAgAAIA6AAQA+AAAAAtIAAANIgyAAQAAgLgHgEQgGgEgRAAIgUAAQggAAAAAVIAAARQAAAXAbAAIAbAAQAcAAAAgQIAAgDIAyAAIAAAMQAAAagTAMQgQAKgaAAgAgsBMQgkAAgOgKQgPgKAAgZIA1AAQAAAGAFADQAHAEAUAAIATAAQARAAAGgCQAHgDAAgGQAAgGgFgCQgEgDgOAAIgvAAQglAAgNgKQgNgKAAgcQAAgXASgJQAOgHAfAAIAkAAQAxAAAQAJQAOAIABAZIg0AAQgCgGgHgCQgHgCgWAAQgXAAgGACQgHACAAAHQAAAEAGACQAGACATAAIAjAAQArAAAOANQAKAIAAAXQAAAbgPAKQgOAJgtAAgAkOBMQg5AAAAg3IAAggQAAg2A5AAIBNAAQA5AAAAA2IAAAgQAAA3g5AAgAkLgVQgJAGAAAOIAAAMQAAAPAJAGQAIAFATAAIAMAAQAZAAAIgEQAHgFAAgOIAAgSQAAgNgHgFQgIgEgZAAIgMAAQgTAAgIAFgArGBMQg5AAAAg3IAAggQAAg2A5AAIBNAAQA5AAAAA2IAAAgQAAA3g5AAgArDgVQgJAGAAAOIAAAMQAAAPAJAGQAIAFATAAIAMAAQAZAAAIgEQAHgFAAgOIAAgSQAAgNgHgFQgIgEgZAAIgMAAQgTAAgIAFgAzlBMQggAAgQgLQgWgPAAgnIAAgNQAAgkARgPQAPgMAfAAIAlAAQAqAAARAMQASANAAAiIAAAXIh+AAIAAAIQAAAKAIAFQAHAEARAAIAQAAQATAAAGgFQAFgDAAgIIAwAAIAAAGQAAAYgUAKQgQAIggAAgAysgNQAAgMgIgEQgHgEgXAAQgZAAgGAEQgHADAAANIBMAAIAAAAgANWBKIAAhOQAAgVgiAAIgMAAQgjAAAAAdIAABGIg0AAIAAiJIA0AAIAAAWIAAAAQAHgOAOgFQAMgFAWAAQAjAAAQAIQAaANAAAoIAABOgAGbBKIAAiJIA0AAIAACJgABwBKIAAiJIAzAAIAACJgAvYBKIAAhOQAAgVgiAAIgMAAQgjAAAAAdIAABGIg0AAIAAiJIA0AAIAAAWIAAAAQAHgOAOgFQAMgFAWAAQAjAAAQAIQAaANAAAoIAABOgAGbhQIAAgpIA0AAIAAApgABwhQIAAgpIAzAAIAAApgAs0inIAAi6IAyAAIAAAVIABAAQAMgXAkAAIAPAAQAuAAAQAQQAMAMAAAfIAAAYQAAAfgMAMQgQAQguAAIgKAAQgXAAgKgFQgKgFgJgQIAAAAIAABIgAr4k3QgIAFAAAPIAAAOQAAAOAIAGQAHAFAQAAIAcAAQARAAAFgGQAFgFAAgNIAAgQQAAgNgFgFQgFgGgRAAIgcAAQgQAAgHAFgAHVjcQgOgJAAgXIAAgMQAAgaAUgIQAOgFArAAQAYAAAJABQAOADAHAHIAAgMQAAgLgFgEQgFgEgPAAIgeAAQgMAAgEACQgEACAAAHIgyAAQAAgaAOgJQANgIAjAAIA8AAQA2AAAAAxIAABbIgxAAIAAgQQgLAMgHADQgIADgTAAIgkAAIgDAAQgXAAgMgHgAH/kOQgFADAAAJQAAAHAGADQAGADAPAAIAPAAQAYAAAJgEQAGgDAAgIQAAgIgFgDQgHgDgUAAIgXAAQgQAAgFAEgAhfjcQgOgJAAgXIAAgMQAAgaATgIQAOgFArAAQAYAAAJABQANADAHAHIAAgMQAAgLgFgEQgFgEgNAAIgfAAQgLAAgEACQgEACgBAHIgyAAQAAgaAPgJQAMgIAjAAIA7AAQA3AAAAAxIAABbIgxAAIAAgQQgLAMgIADQgHADgTAAIgjAAIgDAAQgYAAgLgHgAg2kOQgFADAAAJQAAAHAGADQAGADAPAAIAPAAQAYAAAIgEQAGgDAAgIQAAgIgFgDQgGgDgTAAIgXAAQgQAAgGAEgASTjVQgkAAgPgKQgPgKAAgZIA2AAQAAAGAFADQAHAEAUAAIASAAQATAAAGgCQAGgDAAgGQAAgGgEgCQgFgDgNAAIgxAAQgkAAgNgKQgOgKAAgdQAAgXATgJQAOgHAfAAIAkAAQAxAAAQAJQAPAIAAAZIg0AAQgCgGgGgCQgHgCgXAAQgXAAgGACQgHACAAAHQAAAEAFACQAHACATAAIAkAAQAqAAAPANQAKAJAAAXQAAAbgPAKQgPAJgsAAgAOwjVQg5AAAAg3IAAghQAAg2A5AAIBNAAQA6AAAAA2IAAAhQAAA3g6AAgAO0k3QgJAGAAAOIAAANQAAAPAJAGQAIAFASAAIANAAQAZAAAHgEQAIgFAAgOIAAgTQAAgNgIgFQgHgEgZAAIgNAAQgSAAgIAFgALljVQguAAgQgQQgMgMAAgfIAAgYQAAgfAMgMQAQgQAuAAIAPAAQAqAAAFAbIAAAAIAAhTIA0AAIAADEIgxAAIAAgaIAAAAQgJAcgpAAgALSk2QgFAFAAANIAAAQQAAANAFAFQAFAGASAAIAeAAQARAAAGgFQAIgGAAgOIAAgOQAAgPgIgFQgGgFgRAAIgeAAQgSAAgFAGgAlQjVQggAAgQgLQgWgPAAgnIAAgOQAAgkARgPQAPgMAfAAIA7AAQA9AAAAAtIAAANIgyAAQAAgLgGgEQgHgEgRAAIgUAAQggAAAAAVIAAASQAAAXAcAAIAaAAQAcAAAAgQIAAgDIAyAAIAAAMQAAAagTAMQgPAKgaAAgAoYjVQggAAgQgLQgWgPAAgnIAAgOQAAgkARgPQAPgMAfAAIAlAAQAqAAARAMQASANAAAiIAAAYIh+AAIAAAIQAAAKAIAFQAHAEARAAIAQAAQATAAAGgFQAFgDAAgIIAwAAIAAAGQAAAYgUAKQgQAIggAAgAnfkvQAAgMgIgEQgHgEgXAAQgZAAgGAEQgHADAAANIBMAAIAAAAgAvNjVQgkAAgPgKQgPgKAAgZIA2AAQAAAGAFADQAHAEAUAAIASAAQATAAAGgCQAGgDAAgGQAAgGgEgCQgFgDgNAAIgxAAQgkAAgNgKQgOgKAAgdQAAgXATgJQAOgHAfAAIAkAAQAxAAAQAJQAPAIAAAZIg0AAQgCgGgGgCQgHgCgXAAQgXAAgGACQgHACAAAHQAAAEAFACQAHACATAAIAkAAQAqAAAPANQAKAJAAAXQAAAbgPAKQgPAJgsAAgAEYjXIAAgjIBUhDIAAAAIhPAAIAAgkICXAAIAAApIhPA9IAAAAIBTAAIAAAkgADJjXIAAiKIA0AAIAACKgABsjXIAAjEIA0AAIAADEgAi+jXIAAiKIAzAAIAACKgA0EjXIAAjEIDVAAIAAAuIiaAAIAAAfICSAAIAAAoIiSAAIAAAgICeAAIAAAvgADJlyIAAgpIA0AAIAAApgAi+lyIAAgpIAzAAIAAApg");
	this.shape.setTransform(-6.625,-0.625);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Símbolo3, new cjs.Rectangle(-139,-41.8,264.8,82.4), null);


(lib.Interpolación44 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFD900").s().p("AzeR0IAAj/IBEAAIAAAcIABAAQARgfAyAAIAVAAQA9AAAWAWQARARAAApIAAAiQAAAqgRARQgWAWg9AAIgPAAQgfAAgOgHQgOgHgMgWIAAAAIAABjgAyMOuQgLAIAAAUIAAATQAAAUALAIQAKAGAWAAIAlAAQAYAAAIgIQAFgHAAgSIAAgWQAAgSgFgGQgIgJgYAAIglAAQgWAAgKAHgAP5QrQgTgNAAgfIAAgQQgBgjAbgLQATgIA7AAQAhAAAOACQARADAKAKIAAgQQAAgPgGgFQgHgFgUAAIgqAAQgQAAgFACQgGADgBAKIhEAAQgBglAVgMQARgLAwAAIBSAAQBLAAAABEIAAB8IhEAAIAAgWQgOAQgLAEQgLAFgaAAIgwAAIgEAAQghAAgPgKgAQxPmQgGAFgBAMQABAKAHADQAJAEAVAAIAUAAQAiAAALgFQAJgEAAgLQAAgLgIgDQgIgFgcAAIggAAQgVAAgIAFgAKkQ1Qg+AAgWgWQgRgRAAgqIAAgiQAAgpARgRQAWgWA+AAIAVAAQA6AAAGAmIABAAIAAhyIBGAAIAAEMIhCAAIAAgjIgBAAQgMAmg4AAgAKKOwQgGAGAAASIAAAWQAAASAGAHQAHAIAYAAIAqAAQAWAAAKgGQALgIAAgUIAAgTQAAgUgLgIQgKgHgWAAIgqAAQgYAAgHAJgAgjQ1QgtAAgUgPQgggUAAg3IAAgSQAAgyAZgUQAUgRArAAIAwAAQA7AAAXAQQAZASAAAwIAAAfIisAAIAAAMQABAOAKAGQAKAFAXAAIAVAAQAaAAAIgGQAHgFAAgKIBCAAIAAAIQAAAhgcAOQgVALgsAAgAAqO5QAAgRgKgFQgKgEgeAAQgjAAgJAEQgJAFAAARIBnAAIAAAAgAN1QyIAAi9IBHAAIAAC9gACXQyIAAi9IBCAAIAAAkIABAAQALgnA7AAQAmAAARASQARARAAAnIgBARIg+AAQAAgTgGgIQgHgIgVAAQgpAAAAAfIAABpgAjvQyIAAhmQAAgUgJgHQgJgHgeAAQgaAAgLAGQgLAIAAASIAABoIhHAAIAAhrQAAgSgKgGQgKgFgfAAQgZAAgKAHQgLAIABAVIAABkIhIAAIAAi9IBFAAIAAAlIAAAAQAGgoA5AAIAbAAQAyAAAUAsQAJgaAOgJQAOgJAeAAIAWAAQAvAAAWAXQATAUAAArIAABqgAq2QyIAAi9IBHAAIAAC9gAuwQyIAAi9IBCAAIAAAkIABAAQAKgnA7AAQAmAAARASQARARAAAnIgBARIg9AAQAAgTgHgIQgHgIgUAAQgpAAAAAfIAABpgAq2NdIAAg3IBHAAIAAA3gANrNWIAvhKIBaAAIhOBKgALSJVQgsAAgVgPQgfgUAAg3IAAgSQAAgyAYgUQAUgRArAAIAyAAQA7AAAXAQQAZASAAAwIAAAfIitAAIAAAMQAAAOALAGQAKAFAXAAIAWAAQAZAAAJgGQAGgFAAgKIBDAAIAAAIQAAAhgcAOQgWALgsAAgAMhHZQAAgRgKgFQgLgEgfAAQgjAAgJAEQgIAFAAARIBoAAIAAAAgAEJJVQgsAAgVgPQgfgUAAg3IAAgSQAAgyAYgUQAUgRArAAIAyAAQA7AAAWAQQAaASAAAwIAAAfIitAAIAAAMQAAAOALAGQAJAFAYAAIAWAAQAaAAAIgGQAGgFAAgKIBDAAIAAAIQgBAhgbAOQgWALgsAAgAFXHZQABgRgLgFQgKgEgfAAQgjAAgIAEQgJAFAAARIBnAAIAAAAgAgaJVQg/AAgVgWQgSgRABgqIAAgiQgBgpASgRQAVgWA/AAIAUAAQA6AAAFAmIABAAIAAhyIBHAAIAAEMIhCAAIAAgjIgBAAQgNAmg3AAgAg0HQQgGAGgBASIAAAWQABASAGAHQAHAIAXAAIApAAQAXAAAKgGQAKgIABgUIAAgTQgBgUgKgIQgKgHgXAAIgpAAQgXAAgHAJgAlMJVQgyAAgUgOQgUgNAAgjIBJAAQAAAJAHAEQAJAEAcAAIAaAAQAYAAAJgCQAJgDgBgJQAAgIgFgEQgHgDgSAAIhCAAQgzgBgSgNQgRgOgBgnQAAggAagNQASgJArAAIAxAAQBEAAAWAMQAUALAAAjIhGAAQgEgJgJgCQgJgCgfAAQggAAgJACQgIACgBAKQAAAGAIACQAIADAbAAIAxAAQA6AAAUASQAOANAAAfQAAAlgVANQgUANg8AAgApaJVQgtAAgUgPQgggUAAg3IAAgSQAAgyAZgUQAUgRArAAIAxAAQA7AAAXAQQAZASAAAwIAAAfIitAAIAAAMQABAOAKAGQAKAFAYAAIAVAAQAaAAAIgGQAHgFAAgKIBCAAIAAAIQAAAhgcAOQgVALgsAAgAoMHZQAAgRgKgFQgKgEgfAAQgjAAgJAEQgJAFAAARIBoAAIAAAAgAt/JVQg+AAgWgWQgRgRAAgqIAAgiQAAgpARgRQAWgWA+AAIAVAAQA6AAAGAmIABAAIAAhyIBHAAIAAEMIhDAAIAAgjIgBAAQgMAmg4AAgAuZHQQgGAGAAASIAAAWQAAASAGAHQAIAIAXAAIAqAAQAXAAAJgGQALgIAAgUIAAgTQAAgUgLgIQgJgHgXAAIgqAAQgXAAgIAJgAORJSIAAkMIBHAAIAAEMgArxC0IAAj+IBFAAIAAAcIABAAQARgfAxAAIAVAAQA+AAAWAWQARARAAAoIAAAiQAAAqgRARQgWAWg+AAIgPAAQgeAAgOgHQgOgHgMgWIgBAAIAABjgAqfgRQgKAIgBATIAAATQABAUAKAIQAKAGAXAAIAlAAQAXAAAIgIQAGgHAAgSIAAgWQAAgRgGgGQgIgJgXAAIglAAQgXAAgKAHgAIMBrQgUgNABgfIAAgQQgBgjAbgLQATgHA7AAQAhAAAOACQASADAJAJIAAgPQAAgPgHgFQgGgFgVAAIgpAAQgRAAgFACQgFADgBAKIhEAAQAAglAUgMQARgLAwAAIBSAAQBLAAAABEIAAB7IhEAAIAAgWQgPAQgKAEQgLAFgaAAIgwAAIgEAAQghAAgPgKgAJEAmQgGAFAAAMQAAAKAIADQAIAEAVAAIAUAAQAiAAALgFQAIgEABgLQAAgLgIgDQgIgFgcAAIgfAAQgWAAgIAFgADBB1QgsAAgWgPQgegUAAg3IAAgSQAAgxAXgUQAVgRArAAIBQAAQBVAAAAA/IAAAQIhFAAQgBgOgIgGQgJgGgYAAIgbAAQgrAAAAAcIAAAZQAAAgAmAAIAkAAQAmAAAAgWIAAgEIBFAAIAAARQAAAigaARQgWAOgkAAgAl6B1QhOAAAAhLIAAgsQAAhLBOAAIBrAAQBNAAAABLIAAAsQAABLhNAAgAl1gQQgMAIAAATIAAARQAAAUAMAIQAMAHAYAAIARAAQAjAAAKgGQALgGgBgTIAAgaQABgSgLgFQgKgHgjAAIgRAAQgYAAgMAIgAGJByIAAi8IBGAAIAAC8gAgRByIAAi8IBGAAIAAC8gAiRByIAAkLIBHAAIAAELgAgRhiIAAg3IBGAAIAAA3gAF+hpIAwhKIBaAAIhPBKgAHNlqQhOAAAAhLIAAgtQAAhLBOAAIBqAAQBPAAAABLIAAAtQAABLhPAAgAHSnwQgMAIAAAUIAAARQAAAUAMAIQALAHAaAAIARAAQAhAAALgGQALgGAAgTIAAgaQAAgTgLgFQgLgHghAAIgRAAQgaAAgLAIgAkflqQhOAAAAhLIAAgtQAAhLBOAAIBrAAQBOAAgBBLIAAAtQABBLhOAAgAkanwQgMAIAAAUIAAARQAAAUAMAIQAMAHAZAAIAQAAQAjAAAKgGQALgGAAgTIAAgaQAAgTgLgFQgKgHgjAAIgQAAQgZAAgMAIgAoslqQgsAAgVgPQgfgUAAg3IAAgSQAAgyAYgUQAUgRArAAIBQAAQBVAAAAA/IAAARIhFAAQAAgPgIgGQgKgGgXAAIgbAAQgsAAAAAdIAAAZQAAAgAmAAIAkAAQAmAAAAgWIAAgEIBFAAIAAARQAAAigaARQgWAOgjAAgAEPltIAAhmQAAgUgIgHQgKgHgdAAQgbAAgKAGQgMAIAAASIAABoIhGAAIAAhrQAAgSgLgGQgJgFggAAQgYAAgKAHQgLAIAAAVIAABkIhGAAIAAi9IBDAAIAAAlIABAAQAFgoA6AAIAbAAQAxAAAUAsQAKgaAOgJQAOgJAeAAIAVAAQAwAAAVAXQAUAUgBArIAABqgAEitUQgTgNAAgfIAAgQQAAgjAagLQATgIA8AAQAgAAAOACQASADAKAKIAAgQQgBgPgGgFQgHgFgUAAIgpAAQgRAAgFACQgGADAAAKIhFAAQAAglAUgMQASgLAvAAIBSAAQBMAAAABEIAAB8IhEAAIAAgWQgPAQgKAEQgMAFgaAAIgwAAIgDAAQghAAgQgKgAFbuZQgHAFAAAMQAAAKAIADQAJAEAUAAIAUAAQAjAAAKgFQAJgEAAgLQAAgLgHgDQgJgFgcAAIgfAAQgVAAgIAFgAOEtKQgtAAgUgPQgggUAAg3IAAgSQAAgyAZgUQAUgRArAAIAxAAQA7AAAXAQQAZASAAAwIAAAfIitAAIAAAMQABAOAKAGQAKAFAXAAIAWAAQAaAAAIgGQAHgFAAgKIBCAAIAAAIQAAAhgcAOQgVALgsAAgAPSvGQAAgRgKgFQgKgEgfAAQgjAAgJAEQgJAFAAARIBoAAIAAAAgAKZtKQhSAAAAhCIAAhLIgjAAIAAgzIAjAAIAAgsIBHAAIAAAsIBvAAIAAAzIhvAAIAABJQAAARAcAAQARAAAFgFQAHgFAAgNIAAgNIA+AAIAAAXQAAAdgTARQgVASgoAAgAp+tKQhPAAAAhLIAAgtQAAhLBPAAIBqAAQBOAAAABLIAAAtQAABLhOAAgAp6vQQgLAIgBAUIAAARQABAUALAIQAMAHAZAAIARAAQAiAAAKgGQALgGAAgTIAAgaQAAgTgLgFQgKgHgiAAIgRAAQgZAAgMAIgACmtNIAAhmQABgUgJgHQgKgHgeAAQgZAAgLAGQgMAIABASIAABoIhHAAIAAhrQAAgSgJgGQgLgFgfAAQgYAAgKAHQgLAIAAAVIAABkIhHAAIAAi9IBEAAIAAAlIABAAQAFgoA6AAIAbAAQAxAAAUAsQAIgaAOgJQAOgJAeAAIAXAAQAuAAAWAXQATAUAAArIAABqgAmatNIAAi9IBDAAIAAAkIABAAQAKgnA6AAQAnAAARASQAQARAAAnIAAARIg9AAQAAgTgHgIQgIgIgTAAQgqAAAAAfIAABpgAwNtNIAAkMIEYAAIAABAIjGAAIAAAyIC9AAIAAA+Ii9AAIAABcgAp3wpIAwhKIBaAAIhPBKg");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-124.7,-113.9,249.4,227.9);


(lib.Interpolación43 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFD900").s().p("AzeR0IAAj/IBEAAIAAAcIABAAQARgfAyAAIAVAAQA9AAAWAWQARARAAApIAAAiQAAAqgRARQgWAWg9AAIgPAAQgfAAgOgHQgOgHgMgWIAAAAIAABjgAyMOuQgLAIAAAUIAAATQAAAUALAIQAKAGAWAAIAlAAQAYAAAIgIQAFgHAAgSIAAgWQAAgSgFgGQgIgJgYAAIglAAQgWAAgKAHgAP5QrQgTgNAAgfIAAgQQgBgjAbgLQATgIA7AAQAhAAAOACQARADAKAKIAAgQQAAgPgGgFQgHgFgUAAIgqAAQgQAAgFACQgGADgBAKIhEAAQgBglAVgMQARgLAwAAIBSAAQBLAAAABEIAAB8IhEAAIAAgWQgOAQgLAEQgLAFgaAAIgwAAIgEAAQghAAgPgKgAQxPmQgGAFgBAMQABAKAHADQAJAEAVAAIAUAAQAiAAALgFQAJgEAAgLQAAgLgIgDQgIgFgcAAIggAAQgVAAgIAFgAKkQ1Qg+AAgWgWQgRgRAAgqIAAgiQAAgpARgRQAWgWA+AAIAVAAQA6AAAGAmIABAAIAAhyIBGAAIAAEMIhCAAIAAgjIgBAAQgMAmg4AAgAKKOwQgGAGAAASIAAAWQAAASAGAHQAHAIAYAAIAqAAQAWAAAKgGQALgIAAgUIAAgTQAAgUgLgIQgKgHgWAAIgqAAQgYAAgHAJgAgjQ1QgtAAgUgPQgggUAAg3IAAgSQAAgyAZgUQAUgRArAAIAwAAQA7AAAXAQQAZASAAAwIAAAfIisAAIAAAMQABAOAKAGQAKAFAXAAIAVAAQAaAAAIgGQAHgFAAgKIBCAAIAAAIQAAAhgcAOQgVALgsAAgAAqO5QAAgRgKgFQgKgEgeAAQgjAAgJAEQgJAFAAARIBnAAIAAAAgAN1QyIAAi9IBHAAIAAC9gACXQyIAAi9IBCAAIAAAkIABAAQALgnA7AAQAmAAARASQARARAAAnIgBARIg+AAQAAgTgGgIQgHgIgVAAQgpAAAAAfIAABpgAjvQyIAAhmQAAgUgJgHQgJgHgeAAQgaAAgLAGQgLAIAAASIAABoIhHAAIAAhrQAAgSgKgGQgKgFgfAAQgZAAgKAHQgLAIABAVIAABkIhIAAIAAi9IBFAAIAAAlIAAAAQAGgoA5AAIAbAAQAyAAAUAsQAJgaAOgJQAOgJAeAAIAWAAQAvAAAWAXQATAUAAArIAABqgAq2QyIAAi9IBHAAIAAC9gAuwQyIAAi9IBCAAIAAAkIABAAQAKgnA7AAQAmAAARASQARARAAAnIgBARIg9AAQAAgTgHgIQgHgIgUAAQgpAAAAAfIAABpgAq2NdIAAg3IBHAAIAAA3gANrNWIAvhKIBaAAIhOBKgALSJVQgsAAgVgPQgfgUAAg3IAAgSQAAgyAYgUQAUgRArAAIAyAAQA7AAAXAQQAZASAAAwIAAAfIitAAIAAAMQAAAOALAGQAKAFAXAAIAWAAQAZAAAJgGQAGgFAAgKIBDAAIAAAIQAAAhgcAOQgWALgsAAgAMhHZQAAgRgKgFQgLgEgfAAQgjAAgJAEQgIAFAAARIBoAAIAAAAgAEJJVQgsAAgVgPQgfgUAAg3IAAgSQAAgyAYgUQAUgRArAAIAyAAQA7AAAWAQQAaASAAAwIAAAfIitAAIAAAMQAAAOALAGQAJAFAYAAIAWAAQAaAAAIgGQAGgFAAgKIBDAAIAAAIQgBAhgbAOQgWALgsAAgAFXHZQABgRgLgFQgKgEgfAAQgjAAgIAEQgJAFAAARIBnAAIAAAAgAgaJVQg/AAgVgWQgSgRABgqIAAgiQgBgpASgRQAVgWA/AAIAUAAQA6AAAFAmIABAAIAAhyIBHAAIAAEMIhCAAIAAgjIgBAAQgNAmg3AAgAg0HQQgGAGgBASIAAAWQABASAGAHQAHAIAXAAIApAAQAXAAAKgGQAKgIABgUIAAgTQgBgUgKgIQgKgHgXAAIgpAAQgXAAgHAJgAlMJVQgyAAgUgOQgUgNAAgjIBJAAQAAAJAHAEQAJAEAcAAIAaAAQAYAAAJgCQAJgDgBgJQAAgIgFgEQgHgDgSAAIhCAAQgzgBgSgNQgRgOgBgnQAAggAagNQASgJArAAIAxAAQBEAAAWAMQAUALAAAjIhGAAQgEgJgJgCQgJgCgfAAQggAAgJACQgIACgBAKQAAAGAIACQAIADAbAAIAxAAQA6AAAUASQAOANAAAfQAAAlgVANQgUANg8AAgApaJVQgtAAgUgPQgggUAAg3IAAgSQAAgyAZgUQAUgRArAAIAxAAQA7AAAXAQQAZASAAAwIAAAfIitAAIAAAMQABAOAKAGQAKAFAYAAIAVAAQAaAAAIgGQAHgFAAgKIBCAAIAAAIQAAAhgcAOQgVALgsAAgAoMHZQAAgRgKgFQgKgEgfAAQgjAAgJAEQgJAFAAARIBoAAIAAAAgAt/JVQg+AAgWgWQgRgRAAgqIAAgiQAAgpARgRQAWgWA+AAIAVAAQA6AAAGAmIABAAIAAhyIBHAAIAAEMIhDAAIAAgjIgBAAQgMAmg4AAgAuZHQQgGAGAAASIAAAWQAAASAGAHQAIAIAXAAIAqAAQAXAAAJgGQALgIAAgUIAAgTQAAgUgLgIQgJgHgXAAIgqAAQgXAAgIAJgAORJSIAAkMIBHAAIAAEMgArxC0IAAj+IBFAAIAAAcIABAAQARgfAxAAIAVAAQA+AAAWAWQARARAAAoIAAAiQAAAqgRARQgWAWg+AAIgPAAQgeAAgOgHQgOgHgMgWIgBAAIAABjgAqfgRQgKAIgBATIAAATQABAUAKAIQAKAGAXAAIAlAAQAXAAAIgIQAGgHAAgSIAAgWQAAgRgGgGQgIgJgXAAIglAAQgXAAgKAHgAIMBrQgUgNABgfIAAgQQgBgjAbgLQATgHA7AAQAhAAAOACQASADAJAJIAAgPQAAgPgHgFQgGgFgVAAIgpAAQgRAAgFACQgFADgBAKIhEAAQAAglAUgMQARgLAwAAIBSAAQBLAAAABEIAAB7IhEAAIAAgWQgPAQgKAEQgLAFgaAAIgwAAIgEAAQghAAgPgKgAJEAmQgGAFAAAMQAAAKAIADQAIAEAVAAIAUAAQAiAAALgFQAIgEABgLQAAgLgIgDQgIgFgcAAIgfAAQgWAAgIAFgADBB1QgsAAgWgPQgegUAAg3IAAgSQAAgxAXgUQAVgRArAAIBQAAQBVAAAAA/IAAAQIhFAAQgBgOgIgGQgJgGgYAAIgbAAQgrAAAAAcIAAAZQAAAgAmAAIAkAAQAmAAAAgWIAAgEIBFAAIAAARQAAAigaARQgWAOgkAAgAl6B1QhOAAAAhLIAAgsQAAhLBOAAIBrAAQBNAAAABLIAAAsQAABLhNAAgAl1gQQgMAIAAATIAAARQAAAUAMAIQAMAHAYAAIARAAQAjAAAKgGQALgGgBgTIAAgaQABgSgLgFQgKgHgjAAIgRAAQgYAAgMAIgAGJByIAAi8IBGAAIAAC8gAgRByIAAi8IBGAAIAAC8gAiRByIAAkLIBHAAIAAELgAgRhiIAAg3IBGAAIAAA3gAF+hpIAwhKIBaAAIhPBKgAHNlqQhOAAAAhLIAAgtQAAhLBOAAIBqAAQBPAAAABLIAAAtQAABLhPAAgAHSnwQgMAIAAAUIAAARQAAAUAMAIQALAHAaAAIARAAQAhAAALgGQALgGAAgTIAAgaQAAgTgLgFQgLgHghAAIgRAAQgaAAgLAIgAkflqQhOAAAAhLIAAgtQAAhLBOAAIBrAAQBOAAgBBLIAAAtQABBLhOAAgAkanwQgMAIAAAUIAAARQAAAUAMAIQAMAHAZAAIAQAAQAjAAAKgGQALgGAAgTIAAgaQAAgTgLgFQgKgHgjAAIgQAAQgZAAgMAIgAoslqQgsAAgVgPQgfgUAAg3IAAgSQAAgyAYgUQAUgRArAAIBQAAQBVAAAAA/IAAARIhFAAQAAgPgIgGQgKgGgXAAIgbAAQgsAAAAAdIAAAZQAAAgAmAAIAkAAQAmAAAAgWIAAgEIBFAAIAAARQAAAigaARQgWAOgjAAgAEPltIAAhmQAAgUgIgHQgKgHgdAAQgbAAgKAGQgMAIAAASIAABoIhGAAIAAhrQAAgSgLgGQgJgFggAAQgYAAgKAHQgLAIAAAVIAABkIhGAAIAAi9IBDAAIAAAlIABAAQAFgoA6AAIAbAAQAxAAAUAsQAKgaAOgJQAOgJAeAAIAVAAQAwAAAVAXQAUAUgBArIAABqgAEitUQgTgNAAgfIAAgQQAAgjAagLQATgIA8AAQAgAAAOACQASADAKAKIAAgQQgBgPgGgFQgHgFgUAAIgpAAQgRAAgFACQgGADAAAKIhFAAQAAglAUgMQASgLAvAAIBSAAQBMAAAABEIAAB8IhEAAIAAgWQgPAQgKAEQgMAFgaAAIgwAAIgDAAQghAAgQgKgAFbuZQgHAFAAAMQAAAKAIADQAJAEAUAAIAUAAQAjAAAKgFQAJgEAAgLQAAgLgHgDQgJgFgcAAIgfAAQgVAAgIAFgAOEtKQgtAAgUgPQgggUAAg3IAAgSQAAgyAZgUQAUgRArAAIAxAAQA7AAAXAQQAZASAAAwIAAAfIitAAIAAAMQABAOAKAGQAKAFAXAAIAWAAQAaAAAIgGQAHgFAAgKIBCAAIAAAIQAAAhgcAOQgVALgsAAgAPSvGQAAgRgKgFQgKgEgfAAQgjAAgJAEQgJAFAAARIBoAAIAAAAgAKZtKQhSAAAAhCIAAhLIgjAAIAAgzIAjAAIAAgsIBHAAIAAAsIBvAAIAAAzIhvAAIAABJQAAARAcAAQARAAAFgFQAHgFAAgNIAAgNIA+AAIAAAXQAAAdgTARQgVASgoAAgAp+tKQhPAAAAhLIAAgtQAAhLBPAAIBqAAQBOAAAABLIAAAtQAABLhOAAgAp6vQQgLAIgBAUIAAARQABAUALAIQAMAHAZAAIARAAQAiAAAKgGQALgGAAgTIAAgaQAAgTgLgFQgKgHgiAAIgRAAQgZAAgMAIgACmtNIAAhmQABgUgJgHQgKgHgeAAQgZAAgLAGQgMAIABASIAABoIhHAAIAAhrQAAgSgJgGQgLgFgfAAQgYAAgKAHQgLAIAAAVIAABkIhHAAIAAi9IBEAAIAAAlIABAAQAFgoA6AAIAbAAQAxAAAUAsQAIgaAOgJQAOgJAeAAIAXAAQAuAAAWAXQATAUAAArIAABqgAmatNIAAi9IBDAAIAAAkIABAAQAKgnA6AAQAnAAARASQAQARAAAnIAAARIg9AAQAAgTgHgIQgIgIgTAAQgqAAAAAfIAABpgAwNtNIAAkMIEYAAIAABAIjGAAIAAAyIC9AAIAAA+Ii9AAIAABcgAp3wpIAwhKIBaAAIhPBKg");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-124.7,-113.9,249.4,227.9);


(lib.Interpolación39 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKzA9QgKgHAAgOQAAgdApAAIAaAAIAAgBQAAgVgZAAQgSAAgMAKIgJgRQAQgNAaAAQAtABAAApIAAA5IgWAAIAAgLQgJANgWAAQgRAAgKgJgAK/AoQAAAFAFAEQAFAEAJAAQAUAAAGgPIAAgMIgYAAQgVAAAAAOgAHxA4QgPgOAAgXQAAgVAPgOQAPgPAXAAQAXAAAPAPQAOAOAAAVQAAAXgOAOQgPAOgXAAQgXAAgPgOgAICgCQgJAHAAAOQAAAOAJAJQAIAIANAAQAMAAAJgIQAIgJAAgOQAAgOgIgHQgJgJgMAAQgNAAgIAJgAD+A9QgKgHAAgOQAAgdApAAIAaAAIAAgBQAAgVgZAAQgSAAgMAKIgJgRQAQgNAaAAQAtABAAApIAAA5IgWAAIAAgLQgIANgXAAQgRAAgKgJgAELAoQAAAFAFAEQAFAEAJAAQATAAAGgPIAAgMIgYAAQgUAAAAAOgABPA4QgPgOAAgXQAAgVAPgOQAOgPAWAAQAWABAOAOQAOAOAAAWIAAAGIhOAAQADALAIAHQAIAGANAAQARAAAKgKIAMAOQgNAQgaAAQgZAAgPgOgACPAMQgBgLgIgGQgHgHgMAAQgLAAgIAHQgHAGgCALIA4AAIAAAAgAAIA9QgIgIAAgQIAAgvIgQAAIAAgSIAQAAIAAgXIAWAAIAAAXIAbAAIAAASIgbAAIAAAvQAAAOAOAAQAIAAAFgEIAGAQQgIAHgOAAQgQAAgJgJgAhvA9QgKgHAAgOQAAgdApAAIAZAAIAAgBQAAgVgYAAQgSAAgMAKIgJgRQAQgNAaAAQAtABAAApIAAA5IgWAAIAAgLQgJANgWAAQgRAAgKgJgAhjAoQAAAFAFAEQAFAEAJAAQAUAAAFgPIAAgMIgYAAQgUAAAAAOgAn1A4QgPgOAAgXQAAgVAPgOQAPgPAXAAQAXAAAPAPQAOAOAAAVQAAAXgOAOQgPAOgXAAQgXAAgPgOgAnkgCQgJAHAAAOQAAAOAJAJQAIAIANAAQAMAAAJgIQAIgJAAgOQAAgOgIgHQgJgJgMAAQgNAAgIAJgAJiBEIAAhhIAWAAIAAAOQAKgQAZAAIAAAXIgGgBQgNAAgHAIQgIAHAAAPIAAAvgAG0BEIAAg1QAAgZgXAAQgMAAgIAHQgHAIAAAOIAAAxIgYAAIAAiIIAYAAIAAAyQALgNAVAAQATAAALALQAMAMAAAUIAAA4gAioBEIAAg1QAAgZgWAAQgMAAgHAHQgHAIAAAOIAAAxIgXAAIAAg1QAAgZgWAAQgMAAgHAHQgHAIAAAOIAAAxIgXAAIAAhhIAWAAIAAANQALgOAVgBQAXAAALARQAMgRAZAAQASAAALALQALAMAAAUIAAA4gAmEBEIAAhhIAWAAIAAAOQAKgQAZAAIAAAXIgGgBQgNAAgHAIQgIAHAAAPIAAAvgApFBEIAAhOIgQAAIAAgSIAQAAIAAgGQAAgRAJgIQAJgKARAAQANAAAIAFIgGASQgGgEgHAAQgPAAAAAQIAAAGIAcAAIAAASIgbAAIAABOgAp+BEIAAg1QAAgZgXAAQgNAAgHAHQgIAIAAAOIAAAxIgXAAIAAhhIAWAAIAAANQALgOAXgBQATAAALALQALAMAAAUIAAA4gAsCBEIAAiAIAZAAIAACAgAnfgqIAZgaIAbAAIggAag");
	this.shape.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77,-7,154.1,14);


(lib.Interpolación37 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F6100D").s().p("AsMDbQhaAAhBhBQhAhAAAhaQAAhaBAhAQBBg/BagBIYZAAQBbABA/A/QBBBAAABaQAABahBBAQg/BBhbAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100,-21.8,200,43.7);


(lib.Interpolación36 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F6100D").s().p("AsMDbQhaAAhBhBQhAhAAAhaQAAhaBAhAQBBg/BagBIYZAAQBbABA/A/QBBBAAABaQAABahBBAQg/BBhbAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100,-21.8,200,43.7);


(lib.Interpolación33 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKzA9QgKgHAAgOQAAgdApAAIAaAAIAAgBQAAgVgZAAQgSAAgMAKIgJgRQAQgNAaAAQAtABAAApIAAA5IgWAAIAAgLQgJANgWAAQgRAAgKgJgAK/AoQAAAFAFAEQAFAEAJAAQAUAAAGgPIAAgMIgYAAQgVAAAAAOgAHxA4QgPgOAAgXQAAgVAPgOQAPgPAXAAQAXAAAPAPQAOAOAAAVQAAAXgOAOQgPAOgXAAQgXAAgPgOgAICgCQgJAHAAAOQAAAOAJAJQAIAIANAAQAMAAAJgIQAIgJAAgOQAAgOgIgHQgJgJgMAAQgNAAgIAJgAD+A9QgKgHAAgOQAAgdApAAIAaAAIAAgBQAAgVgZAAQgSAAgMAKIgJgRQAQgNAaAAQAtABAAApIAAA5IgWAAIAAgLQgIANgXAAQgRAAgKgJgAELAoQAAAFAFAEQAFAEAJAAQATAAAGgPIAAgMIgYAAQgUAAAAAOgABPA4QgPgOAAgXQAAgVAPgOQAOgPAWAAQAWABAOAOQAOAOAAAWIAAAGIhOAAQADALAIAHQAIAGANAAQARAAAKgKIAMAOQgNAQgaAAQgZAAgPgOgACPAMQgBgLgIgGQgHgHgMAAQgLAAgIAHQgHAGgCALIA4AAIAAAAgAAIA9QgIgIAAgQIAAgvIgQAAIAAgSIAQAAIAAgXIAWAAIAAAXIAbAAIAAASIgbAAIAAAvQAAAOAOAAQAIAAAFgEIAGAQQgIAHgOAAQgQAAgJgJgAhvA9QgKgHAAgOQAAgdApAAIAZAAIAAgBQAAgVgYAAQgSAAgMAKIgJgRQAQgNAaAAQAtABAAApIAAA5IgWAAIAAgLQgJANgWAAQgRAAgKgJgAhjAoQAAAFAFAEQAFAEAJAAQAUAAAFgPIAAgMIgYAAQgUAAAAAOgAn1A4QgPgOAAgXQAAgVAPgOQAPgPAXAAQAXAAAPAPQAOAOAAAVQAAAXgOAOQgPAOgXAAQgXAAgPgOgAnkgCQgJAHAAAOQAAAOAJAJQAIAIANAAQAMAAAJgIQAIgJAAgOQAAgOgIgHQgJgJgMAAQgNAAgIAJgAJiBEIAAhhIAWAAIAAAOQAKgQAZAAIAAAXIgGgBQgNAAgHAIQgIAHAAAPIAAAvgAG0BEIAAg1QAAgZgXAAQgMAAgIAHQgHAIAAAOIAAAxIgYAAIAAiIIAYAAIAAAyQALgNAVAAQATAAALALQAMAMAAAUIAAA4gAioBEIAAg1QAAgZgWAAQgMAAgHAHQgHAIAAAOIAAAxIgXAAIAAg1QAAgZgWAAQgMAAgHAHQgHAIAAAOIAAAxIgXAAIAAhhIAWAAIAAANQALgOAVgBQAXAAALARQAMgRAZAAQASAAALALQALAMAAAUIAAA4gAmEBEIAAhhIAWAAIAAAOQAKgQAZAAIAAAXIgGgBQgNAAgHAIQgIAHAAAPIAAAvgApFBEIAAhOIgQAAIAAgSIAQAAIAAgGQAAgRAJgIQAJgKARAAQANAAAIAFIgGASQgGgEgHAAQgPAAAAAQIAAAGIAcAAIAAASIgbAAIAABOgAp+BEIAAg1QAAgZgXAAQgNAAgHAHQgIAIAAAOIAAAxIgXAAIAAhhIAWAAIAAANQALgOAXgBQATAAALALQALAMAAAUIAAA4gAsCBEIAAiAIAZAAIAACAgAnfgqIAZgaIAbAAIggAag");
	this.shape.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77,-7,154.1,14);


(lib.Interpolación21 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.fondo2();
	this.instance.setTransform(-476.25,-300,1.5,1.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-476.2,-300,952.5,600);


(lib.Interpolación20 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.fondo2();
	this.instance.setTransform(-476.25,-300,1.5,1.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-476.2,-300,952.5,600);


(lib.Interpolación13 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.Recurso125años();
	this.instance.setTransform(-100,-100,0.9999,0.9999);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100,-100,200,200);


(lib.Interpolación10 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FED800").s().p("AXaH1QgSgMAAgeIAAgOQAAgiAZgKQASgIA3AAQAfAAANACQARADAJAJIAAgPQAAgOgGgFQgGgFgTAAIgoAAQgPAAgFACQgFADgBAJIhBAAQAAgiATgMQARgKAtAAIBOAAQBHAAAABAIAAB1IhAAAIAAgUQgOAPgKAEQgLAEgYAAIguAAIgEAAQgfAAgOgJgAYPG0QgGAEAAAMQAAAJAIADQAIAEATAAIATAAQAgAAALgFQAIgEAAgKQAAgLgHgDQgIgEgaAAIgeAAQgUAAgIAFgAEQH1QgSgMAAgeIAAgOQAAgiAZgKQASgIA3AAQAfAAANACQARADAJAJIAAgPQAAgOgGgFQgGgFgTAAIgoAAQgPAAgFACQgFADgBAJIhBAAQAAgiATgMQARgKAtAAIBOAAQBHAAAABAIAAB1IhAAAIAAgUQgOAPgKAEQgLAEgYAAIguAAIgEAAQgfAAgOgJgAFFG0QgGAEAAAMQAAAJAIADQAIAEATAAIATAAQAgAAALgFQAIgEAAgKQAAgLgHgDQgIgEgaAAIgeAAQgUAAgIAFgAo0H1QgSgMAAgeIAAgOQAAgiAZgKQASgIA3AAQAfAAANACQARADAJAJIAAgPQAAgOgGgFQgGgFgTAAIgoAAQgPAAgFACQgFADgBAJIhBAAQAAgiATgMQARgKAtAAIBOAAQBHAAAABAIAAB1IhAAAIAAgUQgOAPgKAEQgLAEgYAAIguAAIgEAAQgfAAgOgJgAn/G0QgGAEAAAMQAAAJAIADQAIAEATAAIATAAQAgAAALgFQAIgEAAgKQAAgLgHgDQgIgEgaAAIgeAAQgUAAgIAFgAPeH+QhKAAAAhHIAAgqQAAhHBKAAIBlAAQBKAAAABHIAAAqQAABHhKAAgAPjF/QgLAIAAATIAAAQQAAATALAIQAKAHAYAAIAQAAQAhAAAKgGQAJgGAAgSIAAgYQAAgSgJgGQgKgGghAAIgQAAQgYAAgKAHgAJnH+QgqAAgUgOQgdgTAAg0IAAgRQAAgvAXgTQATgQAoAAIBMAAQBQAAAAA7IAAAQIhBAAQAAgOgIgFQgJgGgWAAIgaAAQgpAAAAAcIAAAXQAAAfAkAAIAiAAQAkAAAAgVIAAgEIBBAAIAAAPQAAAhgYAQQgVANghAAgAttH+QgqAAgUgOQgdgTAAg0IAAgRQAAgvAXgTQATgQAoAAIBMAAQBQAAAAA7IAAAQIhBAAQAAgOgIgFQgJgGgWAAIgaAAQgpAAAAAcIAAAXQAAAfAkAAIAiAAQAkAAAAgVIAAgEIBBAAIAAAPQAAAhgYAQQgVANghAAgA2JH+QhKAAAAhHIAAgqQAAhHBKAAIBkAAQBKAAAABHIAAAqQAABHhKAAgA2FF/QgLAIAAATIAAAQQAAATALAIQALAHAYAAIAQAAQAgAAAKgGQAKgGAAgSIAAgYQAAgSgKgGQgKgGggAAIgQAAQgYAAgLAHgAbiH7IAAj9IBDAAIAAD9gAViH7IAAhmQAAgbgsAAIgPAAQguAAAAAnIAABaIhDAAIAAiyIBDAAIAAAcIABAAQAIgRASgIQAQgGAdAAQAtAAAVALQAiARAAAzIAABmgAMkH7IAAiyIBDAAIAACygABfH7IiRi4IAAAAIAAC4IhOAAIAAj9IB4AAICRC4IABAAIAAi4IBOAAIAAD9gAqwH7IAAiyIBDAAIAACygAw1H7IAAiyIBDAAIAACygAyuH7IAAj9IBDAAIAAD9gA8kH7IAAj9IDTAAQA0AAAWAZQASAUAAAqIAAAVQAAAigPAVQgTAbgmAAIiaAAIAAA/gA7XF9IB5AAQAZAAAAgbIAAgKQAAgbggAAIhyAAgAMkEyIAAg0IBDAAIAAA0gAw1EyIAAg0IBDAAIAAA0gAq6ErIAthFIBVAAIhKBFgAvNDIIAAjwIBBAAIAAAaIABAAQAQgdAvAAIATAAQA7AAAVAVQAQAQAAAmIAAAgQAAAngQAQQgVAVg7AAIgNAAQgeAAgMgGQgOgHgLgVIgBAAIAABegAt/ANQgLAHAAATIAAASQAAATALAHQAJAHAVAAIAkAAQAWAAAHgIQAGgHAAgRIAAgVQAAgQgGgHQgHgIgWAAIgkAAQgVAAgJAHgAi0CDQgSgMAAgeIAAgOQAAgiAZgKQASgIA3AAQAfAAANACQARADAJAJIAAgPQAAgOgGgFQgGgEgTAAIgoAAQgPAAgFABQgFADgBAJIhBAAQAAghATgMQARgKAtAAIBOAAQBGAAAAA/IAAB1Ig/AAIAAgUQgOAPgKAEQgLAEgYAAIguAAIgEAAQgfAAgOgJgAh/BCQgGAEAAAMQAAAJAIADQAIAEATAAIATAAQAgAAALgFQAIgEAAgKQAAgLgHgDQgIgEgaAAIgeAAQgUAAgIAFgAqpCDQgSgMAAgeIAAgOQAAgiAZgKQASgIA4AAQAfAAANACQARADAJAJIAAgPQAAgOgGgFQgHgEgTAAIgnAAQgPAAgFABQgGADAAAJIhBAAQAAghATgMQAQgKAtAAIBOAAQBHAAAAA/IAAB1IhAAAIAAgUQgOAPgKAEQgKAEgZAAIguAAIgDAAQgfAAgPgJgApzBCQgHAEAAAMQAAAJAIADQAIAEAUAAIATAAQAgAAAKgFQAIgEAAgKQAAgLgGgDQgIgEgbAAIgdAAQgVAAgHAFgAJjCMQgqAAgUgOQgdgTAAg0IAAgRQAAguAXgTQATgQAoAAIAvAAQA4AAAWAPQAXARAAAsIAAAeIijAAIAAALQAAAOAKAFQAKAFAVAAIAVAAQAZAAAIgGQAFgEAAgKIA/AAIAAAHQAAAggaANQgVAKgpAAgAKtAXQAAgQgKgEQgJgEgeAAQggAAgJAEQgIAEAAAQIBiAAIAAAAgAFKCMQgvAAgTgNQgTgNAAggIBGAAQAAAIAGAEQAJAEAaAAIAYAAQAYAAAIgCQAIgDAAgIQAAgIgGgDQgGgEgRAAIg/AAQgvAAgRgNQgRgNAAglQAAgeAXgLQASgJApAAIAuAAQBBAAAUALQATALAAAfIhDAAQgCgIgJgCQgJgBgeAAQgeAAgIABQgIACAAAJQAAAGAHACQAIADAZAAIAvAAQA2AAATARQANAMAAAeQAAAjgTAMQgTAMg5AAgAMUCJIAAixIA/AAIAAAiIABAAQAJglA4AAQAlAAAPARQAQAQAAAkIAAAQIg7AAQAAgSgGgHQgHgJgTAAQgnAAAAAeIAABjgAmkCJIAAixIA/AAIAAAiIABAAQAJglA4AAQAlAAAPARQAQAQAAAkIAAAQIg7AAQAAgSgGgHQgHgJgTAAQgnAAAAAeIAABjgAlKipIAAjxIBBAAIAAAaIABAAQAQgdAvAAIATAAQA7AAAVAVQAQAQAAAnIAAAgQAAAngQAQQgVAVg7AAIgNAAQgeAAgMgGQgOgHgLgVIgBAAIAABegAj8lkQgLAHAAATIAAASQAAATALAHQAJAHAVAAIAkAAQAWAAAHgIQAGgHAAgRIAAgVQAAgQgGgHQgHgIgWAAIgkAAQgVAAgJAHgAHOjuQgSgMAAgeIAAgOQAAgiAZgKQASgIA3AAQAfAAANACQARADAJAJIAAgPQAAgOgGgFQgGgFgTAAIgoAAQgPAAgFACQgFADgBAJIhBAAQAAgiATgMQARgKAtAAIBOAAQBHAAAABAIAAB1IhAAAIAAgUQgOAPgKAEQgLAEgYAAIguAAIgEAAQgfAAgOgJgAIDkvQgGAEAAAMQAAAJAIADQAIAEATAAIATAAQAgAAALgFQAIgEAAgKQAAgLgHgDQgIgEgaAAIgeAAQgUAAgIAFgAgmjuQgSgMAAgeIAAgOQAAgiAZgKQASgIA3AAQAfAAANACQARADAJAJIAAgPQAAgOgGgFQgHgFgTAAIgnAAQgPAAgFACQgGADAAAJIhAAAQAAgiATgMQAQgKAsAAIBOAAQBHAAAABAIAAB1IhAAAIAAgUQgOAPgKAEQgKAEgZAAIguAAIgDAAQgeAAgPgJgAAPkvQgHAEAAAMQAAAJAIADQAIAEAUAAIATAAQAgAAAKgFQAIgEAAgKQAAgLgGgDQgIgEgbAAIgdAAQgVAAgHAFgAQOjlQgqAAgUgOQgdgTAAg0IAAgRQAAgvAXgTQATgQAoAAIAvAAQA4AAAWAPQAXARAAAtIAAAeIijAAIAAALQAAAOAKAFQAKAFAVAAIAVAAQAZAAAIgGQAFgEAAgKIA/AAIAAAHQAAAggaANQgVAKgpAAgARYlaQAAgQgKgEQgJgFgeAAQggAAgJAFQgIAEAAAQIBiAAIAAAAgAMvjlQhNAAAAg+IAAhHIghAAIAAgwIAhAAIAAgqIBEAAIAAAqIBoAAIAAAwIhoAAIAABFQAAAQAaAAQAQAAAGgFQAFgEAAgNIAAgMIA7AAIAAAWQAAAbgSAQQgUARgmAAgAn6jlQgqAAgUgOQgegTAAg0IAAgRQAAgvAXgTQATgQApAAIAvAAQA4AAAVAPQAYARAAAtIAAAeIijAAIAAALQAAAOAKAFQAJAFAWAAIAVAAQAYAAAIgGQAGgEAAgKIA/AAIAAAHQAAAggaANQgVAKgqAAgAmwlaQAAgQgKgEQgJgFgeAAQghAAgIAFQgIAEAAAQIBiAAIAAAAgADejoIAAiyIA/AAIAAAiIABAAQAJglA4AAQAlAAAPARQAQAQAAAlIAAAQIg7AAQAAgSgGgHQgHgJgTAAQgnAAAAAeIAABjgAs2joIAAiyIA/AAIAAAiIABAAQAJglA4AAQAlAAAPARQAQAQAAAlIAAAQIg7AAQAAgSgGgHQgHgJgTAAQgnAAAAAeIAABjgAyMjoIAAj9IDUAAQAzAAAWAZQASAUAAAqIAAAVQAAAigPAVQgSAbgmAAIiaAAIAAA/gAw+lmIB4AAQAaAAAAgbIAAgKQAAgbggAAIhyAAgAAWm4IAthFIBVAAIhKBFg");
	this.shape.setTransform(2.625,-4.9987);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-180.3,-56,365.9,102);


(lib.Interpolación7 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.policias();
	this.instance.setTransform(-157.05,-151,1.5101,1.5101);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-157,-151,314.1,302);


(lib.Interpolación6 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.policias();
	this.instance.setTransform(-157.05,-151,1.5101,1.5101);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-157,-151,314.1,302);


(lib.Interpolación5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.fondo1();
	this.instance.setTransform(300,-300,1,1,0,0,180);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-300,-300,600,600);


(lib.Interpolación4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.fondo1();
	this.instance.setTransform(300,-300,1,1,0,0,180);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-300,-300,600,600);


(lib.Símbolo4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Basica
	this.instance = new lib.Símbolo5("synched",0);
	this.instance.setTransform(-249.6,-67.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:0},23,cjs.Ease.quartOut).wait(60).to({startPosition:0},0).to({_off:true},1).wait(36));

	// Ejecutiva
	this.instance_1 = new lib.Símbolo6("synched",0);
	this.instance_1.setTransform(262,-22.3);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).to({x:0},23,cjs.Ease.quartOut).wait(51).to({startPosition:0},0).to({_off:true},1).wait(36));

	// Ascensos
	this.instance_2 = new lib.Símbolo7("synched",0);
	this.instance_2.setTransform(-249.6,22.4);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).to({x:0},23,cjs.Ease.quartOut).wait(41).to({startPosition:0},0).to({_off:true},1).wait(36));

	// Psico
	this.instance_3 = new lib.Símbolo8("synched",0);
	this.instance_3.setTransform(262,68.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(29).to({_off:false},0).to({x:0},23,cjs.Ease.quartOut).wait(31).to({startPosition:0},0).to({_off:true},1).wait(36));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-347.4,-84.5,707.3,169.2);


(lib.Interpolación35 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.Interpolación37("synched",0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(11));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100,-21.8,200,43.7);


(lib.Interpolación34 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.Interpolación39("synched",0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(9));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77,-7,154.1,14);


(lib.Símbolo12 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKzA+QgKgJAAgNQAAgdApAAIAaAAIAAgCQAAgUgZAAQgSAAgMAKIgJgRQAQgNAaAAQAtAAAAApIAAA7IgWAAIAAgNQgJAOgWAAQgRAAgKgIgAK/AnQAAAHAFADQAFAEAJAAQAUAAAGgPIAAgMIgYAAQgVAAAAANgAHxA3QgPgOAAgWQAAgVAPgOQAPgPAXAAQAXAAAPAPQAOAOAAAVQAAAWgOAOQgPAPgXAAQgXAAgPgPgAICgCQgJAHAAAOQAAAOAJAJQAIAIANAAQAMAAAJgIQAIgJAAgOQAAgOgIgHQgJgJgMABQgNgBgIAJgAD+A+QgKgJAAgNQAAgdApAAIAaAAIAAgCQAAgUgZAAQgSAAgMAKIgJgRQAQgNAaAAQAtAAAAApIAAA7IgWAAIAAgNQgIAOgXAAQgRAAgKgIgAELAnQAAAHAFADQAFAEAJAAQATAAAGgPIAAgMIgYAAQgUAAAAANgABPA3QgPgNAAgXQAAgVAPgOQAOgPAWAAQAWAAAOAOQAOAPAAAWIAAAHIhOAAQADALAIAGQAIAGANAAQARAAAKgLIAMAPQgNAQgaAAQgZAAgPgPgACPALQgBgLgIgFQgHgHgMAAQgLAAgIAHQgHAFgCALIA4AAIAAAAgAAIA+QgIgJAAgQIAAgvIgQAAIAAgSIAQAAIAAgXIAWAAIAAAXIAbAAIAAASIgbAAIAAAuQAAAPAOAAQAIAAAFgEIAGAQQgIAHgOAAQgQAAgJgIgAhvA+QgKgJAAgNQAAgdApAAIAZAAIAAgCQAAgUgYAAQgSAAgMAKIgJgRQAQgNAaAAQAtAAAAApIAAA7IgWAAIAAgNQgJAOgWAAQgRAAgKgIgAhjAnQAAAHAFADQAFAEAJAAQAUAAAFgPIAAgMIgYAAQgUAAAAANgAn1A3QgPgOAAgWQAAgVAPgOQAPgPAXAAQAXAAAPAPQAOAOAAAVQAAAWgOAOQgPAPgXAAQgXAAgPgPgAnkgCQgJAHAAAOQAAAOAJAJQAIAIANAAQAMAAAJgIQAIgJAAgOQAAgOgIgHQgJgJgMABQgNgBgIAJgAJiBFIAAhiIAWAAIAAAOQAKgPAZgBIAAAXIgGAAQgNAAgHAHQgIAHAAAPIAAAwgAG0BFIAAg2QAAgZgXAAQgMAAgIAIQgHAGAAAPIAAAyIgYAAIAAiJIAYAAIAAAzQALgOAVAAQATAAALALQAMALAAAVIAAA5gAioBFIAAg2QAAgZgWAAQgMAAgHAIQgHAGAAAPIAAAyIgXAAIAAg2QAAgZgWAAQgMAAgHAIQgHAGAAAPIAAAyIgXAAIAAhiIAWAAIAAAMQALgOAVAAQAXABALAQQAMgQAZgBQASAAALALQALALAAAVIAAA5gAmEBFIAAhiIAWAAIAAAOQAKgPAZgBIAAAXIgGAAQgNAAgHAHQgIAHAAAPIAAAwgApFBFIAAhPIgQAAIAAgSIAQAAIAAgHQAAgPAJgKQAJgJARAAQANAAAIAGIgGARQgGgEgHAAQgPAAAAAQIAAAGIAcAAIAAASIgbAAIAABPgAp+BFIAAg2QAAgZgXAAQgNAAgHAIQgIAGAAAPIAAAyIgXAAIAAhiIAWAAIAAAMQALgOAXAAQATAAALALQALALAAAVIAAA5gAsCBFIAAiBIAZAAIAACBgAnfgrIAZgZIAbAAIggAZg");
	this.shape.setTransform(0.775,-0.5);

	this.instance = new lib.Interpolación33("synched",0);
	this.instance.setTransform(0.75,-0.5);
	this.instance._off = true;

	this.instance_1 = new lib.Interpolación34("synched",0);
	this.instance_1.setTransform(0.75,-0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.instance}]},1).to({state:[{t:this.instance_1}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({_off:true},1).wait(1));

	// Capa_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F6100D").s().p("AsMDbQhaAAhBhBQhAhAAAhaQAAhaBAhAQBBg/BagBIYZAAQBbABA/A/QBBBAAABaQAABahBBAQg/BBhbAAg");

	this.instance_2 = new lib.Interpolación35("synched",0);
	this.instance_2._off = true;

	this.instance_3 = new lib.Interpolación36("synched",0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_3}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({_off:false},0).to({_off:true},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100,-21.8,200,43.7);


// stage content:
(lib._300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [274];
	// timeline functions:
	this.frame_274 = function() {
		if(this.looped === undefined) this.looped = 0;
		
		this.looped++;
		
		if(this.looped < 3){
		    this.gotoAndPlay(231);
		} else {
		    this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(274).call(this.frame_274).wait(2));

	// Logo_OFIPOL
	this.instance = new lib.logotipoprincipalofipol04();
	this.instance.setTransform(29,24);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(276));

	// Capa_18
	this.instance_1 = new lib.Interpolación43("synched",0);
	this.instance_1.setTransform(153.7,725.65);
	this.instance_1._off = true;

	this.instance_2 = new lib.Interpolación44("synched",0);
	this.instance_2.setTransform(151.6,296.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_1}]},208).to({state:[{t:this.instance_2}]},15).to({state:[{t:this.instance_2}]},51).to({state:[{t:this.instance_2}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(208).to({_off:false},0).to({_off:true,x:151.6,y:296.15},15,cjs.Ease.circOut).wait(53));

	// BTN
	this.instance_3 = new lib.Símbolo12();
	this.instance_3.setTransform(149.7,527.7,0.005,0.0229,0,0,0,10,2.2);
	this.instance_3._off = true;
	new cjs.ButtonHelper(this.instance_3, 0, 1, 2);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(215).to({_off:false},0).to({regX:0,regY:0,scaleX:1,scaleY:1},15,cjs.Ease.backOut).wait(25).to({regY:-1.2,scaleX:1.2,scaleY:1.1991,x:148.7,y:524},10,cjs.Ease.quintInOut).to({regY:0,scaleX:1,scaleY:1,x:149.7,y:527.7},9,cjs.Ease.quartInOut).wait(2));

	// Capa_14
	this.instance_4 = new lib.Símbolo11("synched",0);
	this.instance_4.setTransform(-192.65,450.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(162).to({_off:false},0).to({regX:0.2,regY:0.2,scaleX:0.8365,scaleY:0.8367,x:152.3,y:452.55,alpha:1},12,cjs.Ease.quartOut).wait(23).to({startPosition:0},0).to({x:561.9,y:461.55,alpha:0},13,cjs.Ease.quartIn).to({_off:true},1).wait(65));

	// Capa_13
	this.instance_5 = new lib.Símbolo10("synched",0);
	this.instance_5.setTransform(505.7,329.6);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(150).to({_off:false},0).to({regX:0.2,regY:0.2,scaleX:0.8465,scaleY:0.8469,x:150.65,y:329.55,alpha:1},12,cjs.Ease.quartOut).wait(35).to({startPosition:0},0).to({x:-209.2,y:327.5,alpha:0},13,cjs.Ease.quartIn).to({_off:true},1).wait(65));

	// Modalidades
	this.instance_6 = new lib.Símbolo9("synched",0);
	this.instance_6.setTransform(-188.8,205.5);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(138).to({_off:false},0).to({scaleX:0.8236,scaleY:0.8237,x:153.4,y:205.45,alpha:1},12,cjs.Ease.quartOut).wait(47).to({startPosition:0},0).to({x:443.6,y:205.1,alpha:0},13,cjs.Ease.quartIn).to({_off:true},1).wait(65));

	// Fondo_2
	this.instance_7 = new lib.Interpolación20("synched",0);
	this.instance_7.setTransform(780.25,300);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.instance_8 = new lib.Interpolación21("synched",0);
	this.instance_8.setTransform(-103.75,300);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_7}]},127).to({state:[{t:this.instance_8}]},19).wait(130));
	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(127).to({_off:false},0).to({_off:true,x:-103.75,alpha:1},19,cjs.Ease.quartOut).wait(130));

	// Oposiciones
	this.instance_9 = new lib.Símbolo4("synched",0);
	this.instance_9.setTransform(144.3,344.85);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(58).to({_off:false},0).wait(84).to({startPosition:0},0).to({_off:true},1).wait(133));

	// Especializados_en_oposiciones
	this.instance_10 = new lib.Símbolo3();
	this.instance_10.setTransform(-144,196.55);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(53).to({_off:false},0).to({x:157.85,y:198.9},13,cjs.Ease.circOut).wait(76).to({_off:true},1).wait(133));

	// _25_años
	this.instance_11 = new lib.Interpolación13("synched",0);
	this.instance_11.setTransform(218.75,418.65,1,1,37.2264);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(50).to({_off:false},0).to({regX:0.4,regY:0.2,scaleX:0.575,scaleY:0.575,rotation:0,x:147.45,y:517.1,alpha:1},8,cjs.Ease.circInOut).wait(84).to({startPosition:0},0).to({_off:true},1).wait(133));

	// Fondo2
	this.instance_12 = new lib.Interpolación5("synched",0);
	this.instance_12.setTransform(211.3,300);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(47).to({_off:false},0).to({alpha:1},7).wait(88).to({startPosition:0},0).to({_off:true},1).wait(133));

	// Preparate_
	this.instance_13 = new lib.Interpolación10("synched",0);
	this.instance_13.setTransform(150.45,194.6,0.0027,0.0089,0,0,0,0,5.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({regX:0.1,regY:-1.2,scaleX:0.706,scaleY:0.7057,x:150.55,y:193.4},23,cjs.Ease.circOut).wait(31).to({startPosition:0},0).to({_off:true},1).wait(221));

	// Policias
	this.instance_14 = new lib.Interpolación6("synched",0);
	this.instance_14.setTransform(481.05,449);

	this.instance_15 = new lib.Interpolación7("synched",0);
	this.instance_15.setTransform(199.05,449);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_14}]}).to({state:[{t:this.instance_15}]},23).to({state:[{t:this.instance_15}]},31).to({state:[]},1).wait(221));
	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({_off:true,x:199.05},23,cjs.Ease.quartOut).wait(253));

	// Fondo1
	this.instance_16 = new lib.Interpolación4("synched",0);
	this.instance_16.setTransform(0,300);

	this.instance_17 = new lib.Interpolación5("synched",0);
	this.instance_17.setTransform(211.3,300);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_16}]}).to({state:[{t:this.instance_17}]},23).to({state:[{t:this.instance_17}]},31).to({state:[]},1).wait(221));
	this.timeline.addTween(cjs.Tween.get(this.instance_16).to({_off:true,x:211.3},23,cjs.Ease.quartOut).wait(253));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-430,300,1686.5,539.7);
// library properties:
lib.properties = {
	id: 'F6D59528AD23487592015ACAE3DC2E4B',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/fondo2.png?1770384768062", id:"fondo2"},
		{src:"images/fondo1.png?1770384768063", id:"fondo1"},
		{src:"images/logotipoprincipalofipol04.png?1770384768063", id:"logotipoprincipalofipol04"},
		{src:"images/policias.png?1770384768063", id:"policias"},
		{src:"images/Recurso125años.png?1770384768063", id:"Recurso125años"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['F6D59528AD23487592015ACAE3DC2E4B'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;